# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: clientmessages.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class EBaseClientMessages(betterproto.Enum):
    CM_CustomGameEvent = 280
    CM_CustomGameEventBounce = 281
    CM_ClientUIEvent = 282
    CM_DevPaletteVisibilityChanged = 283
    CM_WorldUIControllerHasPanelChanged = 284
    CM_RotateAnchor = 285
    CM_MAX_BASE = 300


class EClientUIEvent(betterproto.Enum):
    EClientUIEvent_Invalid = 0
    EClientUIEvent_DialogFinished = 1
    EClientUIEvent_FireOutput = 2


@dataclass
class CClientMsg_CustomGameEvent(betterproto.Message):
    event_name: str = betterproto.string_field(1)
    data: bytes = betterproto.bytes_field(2)


@dataclass
class CClientMsg_CustomGameEventBounce(betterproto.Message):
    event_name: str = betterproto.string_field(1)
    data: bytes = betterproto.bytes_field(2)
    player_slot: int = betterproto.int32_field(3)


@dataclass
class CClientMsg_ClientUIEvent(betterproto.Message):
    event: "EClientUIEvent" = betterproto.enum_field(1)
    ent_ehandle: int = betterproto.uint32_field(2)
    client_ehandle: int = betterproto.uint32_field(3)
    data1: str = betterproto.string_field(4)
    data2: str = betterproto.string_field(5)


@dataclass
class CClientMsg_DevPaletteVisibilityChangedEvent(betterproto.Message):
    visible: bool = betterproto.bool_field(1)


@dataclass
class CClientMsg_WorldUIControllerHasPanelChangedEvent(betterproto.Message):
    has_panel: bool = betterproto.bool_field(1)
    client_ehandle: int = betterproto.uint32_field(2)
    literal_hand_type: int = betterproto.uint32_field(3)


@dataclass
class CClientMsg_RotateAnchor(betterproto.Message):
    angle: float = betterproto.float_field(1)
