# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: connectionless_netmessages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class C2S_CONNECT_Message(betterproto.Message):
    host_version: int = betterproto.uint32_field(1)
    auth_protocol: int = betterproto.uint32_field(2)
    challenge_number: int = betterproto.uint32_field(3)
    reservation_cookie: float = betterproto.fixed64_field(4)
    low_violence: bool = betterproto.bool_field(5)
    encrypted_password: bytes = betterproto.bytes_field(6)
    splitplayers: List["CCLCMsg_SplitPlayerConnect"] = betterproto.message_field(7)
    auth_steam: bytes = betterproto.bytes_field(8)
    challenge_context: str = betterproto.string_field(9)
    use_snp: int = betterproto.sint32_field(10)


@dataclass
class C2S_CONNECTION_Message(betterproto.Message):
    addon_name: str = betterproto.string_field(1)
    use_snp: bool = betterproto.bool_field(2)
