# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_common_overworld.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EOverworldNodeState(betterproto.Enum):
    k_eOverworldNodeState_Invalid = 0
    k_eOverworldNodeState_Locked = 1
    k_eOverworldNodeState_Unlocked = 2


class EOverworldAuditAction(betterproto.Enum):
    k_eOverworldAuditAction_Invalid = 0
    k_eOverworldAuditAction_DevModifyTokens = 1
    k_eOverworldAuditAction_DevClearInventory = 2
    k_eOverworldAuditAction_DevGrantTokens = 3
    k_eOverworldAuditAction_CompletePath = 4
    k_eOverworldAuditAction_ClaimEncounterReward = 5
    k_eOverworldAuditAction_DevResetNode = 6
    k_eOverworldAuditAction_DevResetPath = 7
    k_eOverworldAuditAction_MatchRewardsFull = 8
    k_eOverworldAuditAction_MatchRewardsHalf = 9
    k_eOverworldAuditAction_EventActionTokenGrant = 10
    k_eOverworldAuditAction_TokenTraderLost = 11
    k_eOverworldAuditAction_TokenTraderGained = 12
    k_eOverworldAuditAction_EncounterRewardTokenCost = 13
    k_eOverworldAuditAction_EncounterRewardTokenReward = 14
    k_eOverworldAuditAction_SupportGrantTokens = 16
    k_eOverworldAuditAction_TokenGiftSent = 17


class CMsgClientToGCOverworldGetUserDataResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidOverworld = 5


class CMsgClientToGCOverworldCompletePathResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidOverworld = 5
    k_eInvalidPath = 6
    k_eNotEnoughTokens = 7
    k_ePathIsLocked = 8
    k_ePathAlreadyUnlocked = 9


class CMsgClientToGCOverworldClaimEncounterRewardResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidOverworld = 5
    k_eInvalidNode = 6
    k_eNodeLocked = 7
    k_eRewardAlreadyClaimed = 8
    k_eNodeNotEncounter = 9
    k_eEncounterMissingRewards = 10
    k_eInvalidEncounterRewardStyle = 11
    k_eInvalidEncounterData = 12
    k_eNotEnoughTokensForReward = 13
    k_eNotEnoughResourceForReward = 14


class CMsgClientToGCOverworldVisitEncounterResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidOverworld = 5
    k_eInvalidNode = 6
    k_eNodeLocked = 7
    k_eNodeNotEncounter = 8
    k_eAlreadyVisited = 9


class CMsgClientToGCOverworldMoveToNodeResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidOverworld = 5
    k_eInvalidNode = 6
    k_eNodeLocked = 7


class CMsgClientToGCOverworldTradeTokensResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eNodeLocked = 6
    k_eInvalidOverworld = 7
    k_eInvalidOffer = 8
    k_eNotEnoughTokens = 9
    k_eInvalidNode = 10
    k_eInvalidEncounter = 11
    k_eRewardDoesNotMatchRecipe = 12


class CMsgClientToGCOverworldGiftTokensResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eNodeLocked = 6
    k_eInvalidOverworld = 7
    k_eInvalidGift = 8
    k_eNotEnoughTokens = 9
    k_eInvalidRecipient = 10
    k_eNotEnoughPeriodicResource = 11


class CMsgClientToGCOverworldDevResetAllResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eInvalidOverworld = 6


class CMsgClientToGCOverworldDevResetNodeResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eInvalidOverworld = 6
    k_eInvalidNode = 7


class CMsgClientToGCOverworldDevGrantTokensResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eInvalidOverworld = 6


class CMsgClientToGCOverworldDevClearInventoryResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eInvalidOverworld = 6


class CMsgClientToGCOverworldFeedbackResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNotAllowed = 5
    k_eInvalidOverworld = 6


class CMsgClientToGCOverworldGetDynamicImageResponseEDynamicImageFormat(
    betterproto.Enum
):
    k_eUnknown = 0
    k_ePNG = 1
    k_eData = 2


@dataclass
class CMsgOverworldTokenCount(betterproto.Message):
    token_id: int = betterproto.uint32_field(1)
    token_count: int = betterproto.uint32_field(2)


@dataclass
class CMsgOverworldTokenQuantity(betterproto.Message):
    token_counts: List["CMsgOverworldTokenCount"] = betterproto.message_field(1)


@dataclass
class CMsgOverworldEncounterTokenTreasureData(betterproto.Message):
    reward_options: List[
        "CMsgOverworldEncounterTokenTreasureDataRewardOption"
    ] = betterproto.message_field(1)


@dataclass
class CMsgOverworldEncounterTokenTreasureDataRewardOption(betterproto.Message):
    reward_data: int = betterproto.uint32_field(1)
    token_cost: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)
    token_reward: "CMsgOverworldTokenQuantity" = betterproto.message_field(3)


@dataclass
class CMsgOverworldEncounterTokenQuestData(betterproto.Message):
    quests: List[
        "CMsgOverworldEncounterTokenQuestDataQuest"
    ] = betterproto.message_field(1)


@dataclass
class CMsgOverworldEncounterTokenQuestDataQuest(betterproto.Message):
    reward_data: int = betterproto.uint32_field(1)
    token_cost: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)
    token_reward: "CMsgOverworldTokenQuantity" = betterproto.message_field(3)


@dataclass
class CMsgOverworldHeroList(betterproto.Message):
    hero_ids: List[int] = betterproto.int32_field(1)


@dataclass
class CMsgOverworldEncounterChooseHeroData(betterproto.Message):
    hero_list: "CMsgOverworldHeroList" = betterproto.message_field(1)
    additive: bool = betterproto.bool_field(2)


@dataclass
class CMsgOverworldEncounterProgressData(betterproto.Message):
    choice: int = betterproto.int32_field(1)
    progress: int = betterproto.int32_field(2)
    max_progress: int = betterproto.int32_field(3)
    visited: bool = betterproto.bool_field(4)


@dataclass
class CMsgOverworldEncounterData(betterproto.Message):
    extra_encounter_data: List["CExtraMsgBlock"] = betterproto.message_field(1)


@dataclass
class CMsgOverworldNode(betterproto.Message):
    node_id: int = betterproto.uint32_field(1)
    node_state: "EOverworldNodeState" = betterproto.enum_field(2)
    node_encounter_data: "CMsgOverworldEncounterData" = betterproto.message_field(3)


@dataclass
class CMsgOverworldPath(betterproto.Message):
    path_id: int = betterproto.uint32_field(1)
    path_cost: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)


@dataclass
class CMsgOverworldUserData(betterproto.Message):
    token_inventory: "CMsgOverworldTokenQuantity" = betterproto.message_field(1)
    overworld_nodes: List["CMsgOverworldNode"] = betterproto.message_field(2)
    overworld_paths: List["CMsgOverworldPath"] = betterproto.message_field(3)
    current_node_id: int = betterproto.uint32_field(4)


@dataclass
class CMsgOverworldMatchRewards(betterproto.Message):
    players: List["CMsgOverworldMatchRewardsPlayer"] = betterproto.message_field(1)


@dataclass
class CMsgOverworldMatchRewardsPlayer(betterproto.Message):
    player_slot: int = betterproto.uint32_field(1)
    tokens: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)
    overworld_id: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCOverworldGetUserData(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCOverworldGetUserDataResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldGetUserDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    user_data: "CMsgOverworldUserData" = betterproto.message_field(2)


@dataclass
class CMsgGCToClientOverworldUserDataUpdated(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    user_data: "CMsgOverworldUserData" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCOverworldCompletePath(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    path_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCOverworldCompletePathResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldCompletePathResponseEResponse" = (
        betterproto.enum_field(1)
    )
    claim_response: "CMsgDOTAClaimEventActionResponse" = betterproto.message_field(2)


@dataclass
class CMsgOverworldEncounterPitFighterRewardData(betterproto.Message):
    token_id: int = betterproto.uint32_field(1)
    choice: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCOverworldClaimEncounterReward(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    node_id: int = betterproto.uint32_field(2)
    reward_data: int = betterproto.uint32_field(3)
    periodic_resource_id: int = betterproto.uint32_field(4)
    extra_reward_data: "CMsgOverworldEncounterData" = betterproto.message_field(5)


@dataclass
class CMsgClientToGCOverworldClaimEncounterRewardResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldClaimEncounterRewardResponseEResponse" = (
        betterproto.enum_field(1)
    )
    claim_response: "CMsgDOTAClaimEventActionResponse" = betterproto.message_field(2)
    tokens_received: "CMsgOverworldTokenQuantity" = betterproto.message_field(3)


@dataclass
class CMsgClientToGCOverworldVisitEncounter(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    node_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCOverworldVisitEncounterResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldVisitEncounterResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldMoveToNode(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    node_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCOverworldMoveToNodeResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldMoveToNodeResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldTradeTokens(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    token_offer: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)
    token_request: "CMsgOverworldTokenQuantity" = betterproto.message_field(3)
    recipe: int = betterproto.uint32_field(4)
    encounter_id: int = betterproto.uint32_field(5)


@dataclass
class CMsgClientToGCOverworldTradeTokensResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldTradeTokensResponseEResponse" = (
        betterproto.enum_field(1)
    )
    tokens_received: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCOverworldGiftTokens(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    token_gift: "CMsgOverworldTokenCount" = betterproto.message_field(2)
    recipient_account_id: int = betterproto.uint32_field(3)
    periodic_resource_id: int = betterproto.uint32_field(4)


@dataclass
class CMsgClientToGCOverworldGiftTokensResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldGiftTokensResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldDevResetAll(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCOverworldDevResetAllResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldDevResetAllResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldDevResetNode(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    node_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCOverworldDevResetNodeResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldDevResetNodeResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldDevGrantTokens(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)
    token_quantity: "CMsgOverworldTokenQuantity" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCOverworldDevGrantTokensResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldDevGrantTokensResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldDevClearInventory(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCOverworldDevClearInventoryResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldDevClearInventoryResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldFeedback(betterproto.Message):
    language: int = betterproto.uint32_field(1)
    overworld_id: int = betterproto.uint32_field(2)
    feedback: str = betterproto.string_field(3)


@dataclass
class CMsgClientToGCOverworldFeedbackResponse(betterproto.Message):
    response: "CMsgClientToGCOverworldFeedbackResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCOverworldGetDynamicImage(betterproto.Message):
    magic: int = betterproto.uint32_field(1)
    image_id: int = betterproto.uint32_field(2)
    language: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCOverworldGetDynamicImageResponse(betterproto.Message):
    image_id: int = betterproto.uint32_field(1)
    images: List[
        "CMsgClientToGCOverworldGetDynamicImageResponseImage"
    ] = betterproto.message_field(2)


@dataclass
class CMsgClientToGCOverworldGetDynamicImageResponseImage(betterproto.Message):
    width: int = betterproto.uint32_field(1)
    height: int = betterproto.uint32_field(2)
    format: "CMsgClientToGCOverworldGetDynamicImageResponseEDynamicImageFormat" = (
        betterproto.enum_field(3)
    )
    image_bytes: bytes = betterproto.bytes_field(4)
