# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_usercmd.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


@dataclass
class CDota2UserCmdPB(betterproto.Message):
    base: "CBaseUserCmdPB" = betterproto.message_field(1)
    spectator_query_unit_entindex: int = betterproto.int32_field(2)
    crosshairtrace: "CMsgVector" = betterproto.message_field(3)
    cameraposition_x: int = betterproto.int32_field(4)
    cameraposition_y: int = betterproto.int32_field(5)
    clickbehavior: int = betterproto.uint32_field(6)
    statspanel: int = betterproto.uint32_field(7)
    shoppanel: int = betterproto.uint32_field(8)
    stats_dropdown: int = betterproto.uint32_field(9)
    stats_dropdown_sort: int = betterproto.uint32_field(10)
