# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_clientmessages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EDotaClientMessages(betterproto.Enum):
    DOTA_CM_MapLine = 301
    DOTA_CM_AspectRatio = 302
    DOTA_CM_MapPing = 303
    DOTA_CM_UnitsAutoAttack = 304
    DOTA_CM_SearchString = 307
    DOTA_CM_Pause = 308
    DOTA_CM_ShopViewMode = 309
    DOTA_CM_SetUnitShareFlag = 310
    DOTA_CM_SwapRequest = 311
    DOTA_CM_SwapAccept = 312
    DOTA_CM_WorldLine = 313
    DOTA_CM_RequestGraphUpdate = 314
    DOTA_CM_ItemAlert = 315
    DOTA_CM_ChatWheel = 316
    DOTA_CM_SendStatPopup = 317
    DOTA_CM_BeginLastHitChallenge = 318
    DOTA_CM_UpdateQuickBuy = 319
    DOTA_CM_UpdateCoachListen = 320
    DOTA_CM_CoachHUDPing = 321
    DOTA_CM_RecordVote = 322
    DOTA_CM_UnitsAutoAttackAfterSpell = 323
    DOTA_CM_WillPurchaseAlert = 324
    DOTA_CM_PlayerShowCase = 325
    DOTA_CM_TeleportRequiresHalt = 326
    DOTA_CM_CameraZoomAmount = 327
    DOTA_CM_BroadcasterUsingCamerman = 328
    DOTA_CM_BroadcasterUsingAssistedCameraOperator = 329
    DOTA_CM_EnemyItemAlert = 330
    DOTA_CM_FreeInventory = 331
    DOTA_CM_BuyBackStateAlert = 332
    DOTA_CM_QuickBuyAlert = 333
    DOTA_CM_HeroStatueLike = 334
    DOTA_CM_ModifierAlert = 335
    DOTA_CM_TeamShowcaseEditor = 336
    DOTA_CM_HPManaAlert = 337
    DOTA_CM_GlyphAlert = 338
    DOTA_CM_TeamShowcaseClientData = 339
    DOTA_CM_PlayTeamShowcase = 340
    DOTA_CM_EventCNY2015Cmd = 341
    DOTA_CM_FillEmptySlotsWithBots = 342
    DOTA_CM_DemoHero = 343
    DOTA_CM_AbilityLearnModeToggled = 344
    DOTA_CM_AbilityStartUse = 345
    DOTA_CM_ChallengeSelect = 346
    DOTA_CM_ChallengeReroll = 347
    DOTA_CM_ClickedBuff = 348
    DOTA_CM_CoinWager = 349
    DOTA_CM_ExecuteOrders = 350
    DOTA_CM_XPAlert = 351
    DOTA_CM_EventPointsTip = 353
    DOTA_CM_KillMyHero = 355
    DOTA_CM_QuestStatus = 356
    DOTA_CM_ToggleAutoattack = 357
    DOTA_CM_SpecialAbility = 358
    DOTA_CM_KillcamDamageTaken = 359
    DOTA_CM_SetEnemyStartingPosition = 360
    DOTA_CM_SetDesiredWardPlacement = 361
    DOTA_CM_RollDice = 362
    DOTA_CM_FlipCoin = 363
    DOTA_CM_RequestItemSuggestions = 364
    DOTA_CM_MakeTeamCaptain = 365
    DOTA_CM_CoinWagerToken = 366
    DOTA_CM_RankWager = 367
    DOTA_CM_DismissAllStatPopups = 368
    DOTA_CM_HelpTipSystemStateChanged = 369
    DOTA_CM_ChannelRequiresHalt = 370
    DOTA_CM_RequestBulkCombatLog = 371
    DOTA_CM_AbilityDraftRequestAbility = 372
    DOTA_CM_GuideSelectOption = 373
    DOTA_CM_GuideSelected = 374
    DOTA_CM_DamageReport = 375
    DOTA_CM_SalutePlayer = 376
    DOTA_CM_SprayWheel = 377
    DOTA_CM_TipAlert = 378
    DOTA_CM_EmptyTeleportAlert = 379
    DOTA_CM_RadarAlert = 380
    DOTA_CM_TalentTreeAlert = 381
    DOTA_CM_SetCavernMapVariant = 382
    DOTA_CM_PauseGameOrder = 383
    DOTA_CM_VersusScene_PlayerBehavior = 384
    DOTA_CM_PlayerBounty = 385
    DOTA_CM_PlayerBountyCancel = 386
    DOTA_CM_EmptyItemSlotAlert = 388
    DOTA_CM_AddOverwatchReportMarker = 389
    DOTA_CM_AghsStatusAlert = 390
    DOTA_CM_PerfReport = 391
    DOTA_CM_ContextualTips_Subscribe = 393
    DOTA_CM_ChatMessage = 394
    DOTA_CM_AddCommunicationsReportMarker = 395
    DOTA_CM_AddCommunicationsBlockMarker = 396
    DOTA_CM_NeutralCampAlert = 397
    DOTA_CM_DuelAccepted = 398
    DOTA_CM_ChooseNeutralItem = 399
    DOTA_CM_PlayerDraftPick = 800
    DOTA_CM_PlayerDraftSuggest = 801
    DOTA_CM_PlayerDraftPreferRole = 802
    DOTA_CM_PlayerDraftPreferTeam = 803
    DOTA_CM_ChatWheelAlert = 804
    DOTA_CM_AbilityAlert = 805
    DOTA_CM_AllyAbilityAlert = 806
    DOTA_CM_GiftPlayer = 807
    DOTA_CM_GiftEveryone = 808
    DOTA_CM_SelectOverworldTokenRewards = 809
    DOTA_CM_FacetAlert = 810
    DOTA_CM_InnateAlert = 811
    DOTA_CM_SelectOverworldID = 812
    DOTA_CM_RerollNeutralItem = 813
    DOTA_CM_RoshanTimer = 814


class CDOTAClientMsg_UnitsAutoAttackModeEMode(betterproto.Enum):
    INVALID = -1
    NEVER = 0
    AFTER_SPELLCAST = 1
    ALWAYS = 2


class CDOTAClientMsg_UnitsAutoAttackModeEUnitType(betterproto.Enum):
    NORMAL = 0
    SUMMONED = 1


@dataclass
class CDOTAClientMsg_MapPing(betterproto.Message):
    location_ping: "CDOTAMsg_LocationPing" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_ItemAlert(betterproto.Message):
    item_alert: "CDOTAMsg_ItemAlert" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_EnemyItemAlert(betterproto.Message):
    item_entindex: int = betterproto.int32_field(1)
    rune_type: int = betterproto.int32_field(2)
    item_level: int = betterproto.int32_field(3)
    primary_charges: int = betterproto.int32_field(4)
    secondary_charges: int = betterproto.int32_field(5)
    ability_id: int = betterproto.int32_field(6)
    owner_entindex: int = betterproto.int32_field(7)


@dataclass
class CDOTAClientMsg_ModifierAlert(betterproto.Message):
    buff_internal_index: int = betterproto.int32_field(1)
    target_entindex: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_ClickedBuff(betterproto.Message):
    buff_internal_index: int = betterproto.int32_field(1)
    target_entindex: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_HPManaAlert(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    show_raw_values: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_NeutralCampAlert(betterproto.Message):
    spawner_entindex: int = betterproto.int32_field(1)
    unit_entindex: int = betterproto.int32_field(2)
    stack_request: bool = betterproto.bool_field(3)


@dataclass
class CDOTAClientMsg_GlyphAlert(betterproto.Message):
    negative: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_RadarAlert(betterproto.Message):
    negative: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_MapLine(betterproto.Message):
    mapline: "CDOTAMsg_MapLine" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_AspectRatio(betterproto.Message):
    ratio: float = betterproto.float_field(1)


@dataclass
class CDOTAClientMsg_UnitsAutoAttackMode(betterproto.Message):
    mode: "CDOTAClientMsg_UnitsAutoAttackModeEMode" = betterproto.enum_field(1)
    unit_type: "CDOTAClientMsg_UnitsAutoAttackModeEUnitType" = betterproto.enum_field(2)


@dataclass
class CDOTAClientMsg_UnitsAutoAttackAfterSpell(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_TeleportRequiresHalt(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_ChannelRequiresHalt(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_SearchString(betterproto.Message):
    search: str = betterproto.string_field(1)


@dataclass
class CDOTAClientMsg_Pause(betterproto.Message):
    pass


@dataclass
class CDOTAClientMsg_ShopViewMode(betterproto.Message):
    mode: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_SetUnitShareFlag(betterproto.Message):
    player_id: int = betterproto.int32_field(1)
    flag: int = betterproto.uint32_field(2)
    state: bool = betterproto.bool_field(3)


@dataclass
class CDOTAClientMsg_SwapRequest(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_SwapAccept(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_WorldLine(betterproto.Message):
    worldline: "CDOTAMsg_WorldLine" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_RequestGraphUpdate(betterproto.Message):
    pass


@dataclass
class CDOTAClientMsg_ChatWheel(betterproto.Message):
    chat_message_id: int = betterproto.uint32_field(1)
    param_hero_id: int = betterproto.int32_field(2)
    emoticon_id: int = betterproto.uint32_field(3)


@dataclass
class CDOTAClientMsg_SendStatPopup(betterproto.Message):
    statpopup: "CDOTAMsg_SendStatPopup" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_DismissAllStatPopups(betterproto.Message):
    dismissallmsg: "CDOTAMsg_DismissAllStatPopups" = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_BeginLastHitChallenge(betterproto.Message):
    chosen_lane: int = betterproto.uint32_field(1)
    helper_enabled: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_UpdateQuickBuyItem(betterproto.Message):
    item_ability_id: int = betterproto.int32_field(1)
    purchasable: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_UpdateQuickBuy(betterproto.Message):
    items: List["CDOTAClientMsg_UpdateQuickBuyItem"] = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_RecordVote(betterproto.Message):
    choice_index: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_WillPurchaseAlert(betterproto.Message):
    item_ability_id: int = betterproto.int32_field(1)
    gold_remaining: int = betterproto.uint32_field(2)
    suggestion_player_id: int = betterproto.int32_field(3)


@dataclass
class CDOTAClientMsg_BuyBackStateAlert(betterproto.Message):
    pass


@dataclass
class CDOTAClientMsg_QuickBuyAlert(betterproto.Message):
    item_ability_id: int = betterproto.int32_field(1)
    gold_cost: int = betterproto.int32_field(2)
    item_cooldown_seconds: int = betterproto.int32_field(3)
    show_buyback: bool = betterproto.bool_field(4)


@dataclass
class CDOTAClientMsg_PlayerShowCase(betterproto.Message):
    showcase: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_CameraZoomAmount(betterproto.Message):
    zoom_amount: float = betterproto.float_field(1)


@dataclass
class CDOTAClientMsg_BroadcasterUsingCameraman(betterproto.Message):
    cameraman: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_BroadcasterUsingAssistedCameraOperator(betterproto.Message):
    enabled: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_FillEmptySlotsWithBots(betterproto.Message):
    fillwithbots: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_HeroStatueLike(betterproto.Message):
    owner_player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_EventCNY2015Cmd(betterproto.Message):
    data: bytes = betterproto.bytes_field(1)


@dataclass
class CDOTAClientMsg_DemoHero(betterproto.Message):
    hero_id: int = betterproto.int32_field(1)
    hero_id_to_spawn: int = betterproto.int32_field(2)
    item_defs: List[int] = betterproto.uint32_field(3)
    item_ids: List[int] = betterproto.uint64_field(4)
    style_index: int = betterproto.uint32_field(5)
    keep_existing_demohero: bool = betterproto.bool_field(6)
    item_data: List["CSOEconItem"] = betterproto.message_field(7)
    hero_variant: int = betterproto.int32_field(8)


@dataclass
class CDOTAClientMsg_ChallengeSelect(betterproto.Message):
    event_id: int = betterproto.uint32_field(1)
    slot_id: int = betterproto.uint32_field(2)
    sequence_id: int = betterproto.uint32_field(3)


@dataclass
class CDOTAClientMsg_ChallengeReroll(betterproto.Message):
    event_id: "EEvent" = betterproto.enum_field(1)
    slot_id: int = betterproto.uint32_field(2)
    sequence_id: int = betterproto.uint32_field(3)
    hero_id: int = betterproto.int32_field(4)


@dataclass
class CDOTAClientMsg_CoinWager(betterproto.Message):
    wager_amount: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_CoinWagerToken(betterproto.Message):
    wager_token_item_id: int = betterproto.uint64_field(1)


@dataclass
class CDOTAClientMsg_RankWager(betterproto.Message):
    announce_wager: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_PlayerBounty(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_EventPointsTip(betterproto.Message):
    recipient_player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_ExecuteOrders(betterproto.Message):
    orders: List["CDOTAMsg_UnitOrder"] = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_XPAlert(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    damage_taken: int = betterproto.uint32_field(2)


@dataclass
class CDOTAClientMsg_TalentTreeAlert(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    ability_id: int = betterproto.int32_field(2)
    slot: int = betterproto.int32_field(3)
    learned: bool = betterproto.bool_field(4)


@dataclass
class CDOTAClientMsg_KillcamDamageTaken(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    damage_taken: int = betterproto.uint32_field(2)
    item_type: int = betterproto.uint32_field(3)
    item_ability_id: int = betterproto.int32_field(4)
    hero_name: str = betterproto.string_field(5)
    damage_color: str = betterproto.string_field(6)


@dataclass
class CDOTAClientMsg_KillMyHero(betterproto.Message):
    pass


@dataclass
class CDOTAClientMsg_QuestStatus(betterproto.Message):
    quest_id: int = betterproto.uint32_field(1)
    challenge_id: int = betterproto.uint32_field(2)
    progress: int = betterproto.uint32_field(3)
    goal: int = betterproto.uint32_field(4)
    query: int = betterproto.uint32_field(5)
    fail_gametime: float = betterproto.float_field(6)
    item_ability_id: int = betterproto.int32_field(7)


@dataclass
class CDOTAClientMsg_ToggleAutoattack(betterproto.Message):
    mode: int = betterproto.int32_field(1)
    show_message: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_SpecialAbility(betterproto.Message):
    ability_index: int = betterproto.uint32_field(1)
    target_entindex: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_SetEnemyStartingPosition(betterproto.Message):
    enemy_player_id: int = betterproto.int32_field(1)
    enemy_starting_position: int = betterproto.uint32_field(2)


@dataclass
class CDOTAClientMsg_SetDesiredWardPlacement(betterproto.Message):
    ward_index: int = betterproto.uint32_field(1)
    ward_x: float = betterproto.float_field(2)
    ward_y: float = betterproto.float_field(3)


@dataclass
class CDOTAClientMsg_RollDice(betterproto.Message):
    channel_type: int = betterproto.uint32_field(1)
    roll_min: int = betterproto.uint32_field(2)
    roll_max: int = betterproto.uint32_field(3)


@dataclass
class CDOTAClientMsg_FlipCoin(betterproto.Message):
    channel_type: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_RequestItemSuggestions(betterproto.Message):
    pass


@dataclass
class CDOTAClientMsg_MakeTeamCaptain(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_HelpTipSystemStateChanged(betterproto.Message):
    tip_displayed: bool = betterproto.bool_field(1)


@dataclass
class CDOTAClientMsg_RequestBulkCombatLog(betterproto.Message):
    game_time: float = betterproto.float_field(1)
    duration: float = betterproto.float_field(2)
    recent_player_death: bool = betterproto.bool_field(3)
    player_id: int = betterproto.int32_field(4)


@dataclass
class CDOTAClientMsg_AbilityDraftRequestAbility(betterproto.Message):
    requested_ability_id: int = betterproto.int32_field(1)
    ctrl_is_down: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_GuideSelectOption(betterproto.Message):
    option: int = betterproto.uint32_field(1)
    force_recalculate: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_GuideSelected(betterproto.Message):
    guide_workshop_id: int = betterproto.uint64_field(1)
    is_plus_guide: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_DamageReport(betterproto.Message):
    target_hero_id: int = betterproto.int32_field(1)
    source_hero_id: int = betterproto.int32_field(2)
    damage_amount: int = betterproto.int32_field(3)
    broadcast: bool = betterproto.bool_field(4)


@dataclass
class CDOTAClientMsg_SalutePlayer(betterproto.Message):
    target_player_id: int = betterproto.int32_field(1)
    event_id: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_GiftPlayer(betterproto.Message):
    target_player_id: int = betterproto.int32_field(1)
    item_def_index: int = betterproto.uint32_field(2)


@dataclass
class CDOTAClientMsg_GiftEveryone(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_TipAlert(betterproto.Message):
    tip_text: str = betterproto.string_field(1)


@dataclass
class CDOTAClientMsg_EmptyTeleportAlert(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_SetCavernMapVariant(betterproto.Message):
    map_variant: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_PauseGameOrder(betterproto.Message):
    order_id: int = betterproto.int32_field(1)
    data: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_VersusScene_PlayerBehavior(betterproto.Message):
    behavior: "EDOTAVersusScenePlayerBehavior" = betterproto.enum_field(1)
    play_activity: "VersusScene_PlayActivity" = betterproto.message_field(2)
    chat_wheel: "VersusScene_ChatWheel" = betterproto.message_field(3)
    playback_rate: "VersusScene_PlaybackRate" = betterproto.message_field(4)


@dataclass
class CDOTAClientMsg_EmptyItemSlotAlert(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    slot_index: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_AddOverwatchReportMarker(betterproto.Message):
    target_player_id: int = betterproto.int32_field(1)
    reason: "EOverwatchReportReason" = betterproto.enum_field(2)
    seconds_ago: int = betterproto.uint32_field(4)


@dataclass
class CDOTAClientMsg_AddCommunicationsReportMarker(betterproto.Message):
    target_player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_AddCommunicationsBlockMarker(betterproto.Message):
    target_player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_AghsStatusAlert(betterproto.Message):
    source_player_id: int = betterproto.int32_field(1)
    target_player_id: int = betterproto.int32_field(2)
    target_entindex: int = betterproto.int32_field(3)
    alert_type: int = betterproto.uint32_field(4)


@dataclass
class CDOTAClientMsg_PerfReport(betterproto.Message):
    average_frame_time: float = betterproto.float_field(1)
    max_frame_time: float = betterproto.float_field(2)
    average_compute_time: float = betterproto.float_field(3)
    max_compute_time: float = betterproto.float_field(4)
    average_client_tick_time: float = betterproto.float_field(5)
    max_client_tick_time: float = betterproto.float_field(6)
    average_client_simulate_time: float = betterproto.float_field(7)
    max_client_simulate_time: float = betterproto.float_field(8)
    average_output_time: float = betterproto.float_field(9)
    max_output_time: float = betterproto.float_field(10)
    average_wait_for_rendering_to_complete_time: float = betterproto.float_field(11)
    max_wait_for_rendering_to_complete_time: float = betterproto.float_field(12)
    average_swap_time: float = betterproto.float_field(13)
    max_swap_time: float = betterproto.float_field(14)
    average_frame_update_time: float = betterproto.float_field(15)
    max_frame_update_time: float = betterproto.float_field(16)
    average_idle_time: float = betterproto.float_field(17)
    max_idle_time: float = betterproto.float_field(18)
    average_input_processing_time: float = betterproto.float_field(19)
    max_input_processing_time: float = betterproto.float_field(20)


@dataclass
class CDOTAClientMsg_ContextualTips_Subscribe_Entry(betterproto.Message):
    unsubscribe: bool = betterproto.bool_field(1)
    tip_id: int = betterproto.int32_field(2)
    prior_display_count: int = betterproto.int32_field(3)
    variants_seen: List[int] = betterproto.int32_field(4)


@dataclass
class CDOTAClientMsg_ContextualTips_Subscribe(betterproto.Message):
    tips: List[
        "CDOTAClientMsg_ContextualTips_Subscribe_Entry"
    ] = betterproto.message_field(1)


@dataclass
class CDOTAClientMsg_ChatMessage(betterproto.Message):
    channel_type: int = betterproto.uint32_field(1)
    message_text: str = betterproto.string_field(2)


@dataclass
class CDOTAClientMsg_DuelAccepted(betterproto.Message):
    challenger_player_id: int = betterproto.int32_field(1)
    accepter_player_id: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_ChooseNeutralItem(betterproto.Message):
    neutral_item_index: int = betterproto.int32_field(1)
    target_entindex: int = betterproto.int32_field(2)
    slot_index: int = betterproto.int32_field(3)


@dataclass
class CDOTAClientMsg_RerollNeutralItem(betterproto.Message):
    target_entindex: int = betterproto.int32_field(1)
    slot_index: int = betterproto.int32_field(2)


@dataclass
class CDOTAClientMsg_PlayerDraftPick(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_PlayerDraftSuggest(betterproto.Message):
    player_id: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_PlayerDraftPreferRole(betterproto.Message):
    role_idx: int = betterproto.int32_field(1)
    desired: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_PlayerDraftPreferTeam(betterproto.Message):
    team: int = betterproto.int32_field(1)


@dataclass
class CDOTAClientMsg_AbilityAlert(betterproto.Message):
    ability_entindex: int = betterproto.uint32_field(1)
    ctrl_held: bool = betterproto.bool_field(2)
    owner_entindex: int = betterproto.int32_field(3)
    ability_id: int = betterproto.int32_field(4)
    primary_charges: int = betterproto.uint32_field(5)
    secondary_charges: int = betterproto.uint32_field(6)
    reclaim_time: float = betterproto.float_field(7)


@dataclass
class CDOTAClientMsg_SelectOverworldTokenRewards(betterproto.Message):
    token_ids: List[int] = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_FacetAlert(betterproto.Message):
    facet_strhash: int = betterproto.uint32_field(1)
    hero_entindex: int = betterproto.uint32_field(2)
    ctrl_held: bool = betterproto.bool_field(3)


@dataclass
class CDOTAClientMsg_InnateAlert(betterproto.Message):
    ability_entindex: int = betterproto.uint32_field(1)
    ctrl_held: bool = betterproto.bool_field(2)


@dataclass
class CDOTAClientMsg_SelectOverworldID(betterproto.Message):
    overworld_id: int = betterproto.uint32_field(1)


@dataclass
class CDOTAClientMsg_RoshanTimer(betterproto.Message):
    negative: bool = betterproto.bool_field(1)
