# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_common_lobby.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class ELobbyMemberCoachRequestState(betterproto.Enum):
    k_eLobbyMemberCoachRequestState_None = 0
    k_eLobbyMemberCoachRequestState_Accepted = 1
    k_eLobbyMemberCoachRequestState_Rejected = 2


class LobbyDotaTVDelay(betterproto.Enum):
    LobbyDotaTV_10 = 0
    LobbyDotaTV_120 = 1
    LobbyDotaTV_300 = 2
    LobbyDotaTV_900 = 3


class LobbyDotaPauseSetting(betterproto.Enum):
    LobbyDotaPauseSetting_Unlimited = 0
    LobbyDotaPauseSetting_Limited = 1
    LobbyDotaPauseSetting_Disabled = 2


class CSODOTALobbyState(betterproto.Enum):
    UI = 0
    READYUP = 4
    SERVERSETUP = 1
    RUN = 2
    POSTGAME = 3
    NOTREADY = 5
    SERVERASSIGN = 6


class CSODOTALobbyLobbyType(betterproto.Enum):
    INVALID = -1
    CASUAL_MATCH = 0
    PRACTICE = 1
    COOP_BOT_MATCH = 4
    COMPETITIVE_MATCH = 7
    WEEKEND_TOURNEY = 9
    LOCAL_BOT_MATCH = 10
    SPECTATOR = 11
    EVENT_MATCH = 12
    NEW_PLAYER_POOL = 14
    FEATURED_GAMEMODE = 15


@dataclass
class CMsgLobbyCoachFriendRequest(betterproto.Message):
    coach_account_id: int = betterproto.uint32_field(1)
    player_account_id: int = betterproto.uint32_field(2)
    request_state: "ELobbyMemberCoachRequestState" = betterproto.enum_field(3)


@dataclass
class CMsgLobbyPlayerPlusSubscriptionData(betterproto.Message):
    hero_badges: List[
        "CMsgLobbyPlayerPlusSubscriptionDataHeroBadge"
    ] = betterproto.message_field(1)


@dataclass
class CMsgLobbyPlayerPlusSubscriptionDataHeroBadge(betterproto.Message):
    hero_id: int = betterproto.int32_field(1)
    hero_badge_xp: int = betterproto.uint32_field(2)


@dataclass
class CMsgEventActionData(betterproto.Message):
    action_id: int = betterproto.uint32_field(1)
    action_score: int = betterproto.uint32_field(2)


@dataclass
class CMsgPeriodicResourceData(betterproto.Message):
    periodic_resource_id: int = betterproto.uint32_field(1)
    remaining: int = betterproto.uint32_field(2)
    max: int = betterproto.uint32_field(3)


@dataclass
class CMsgLobbyEventPoints(betterproto.Message):
    event_id: int = betterproto.uint32_field(1)
    account_points: List[
        "CMsgLobbyEventPointsAccountPoints"
    ] = betterproto.message_field(2)


@dataclass
class CMsgLobbyEventPointsAccountPoints(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    normal_points: int = betterproto.uint32_field(2)
    premium_points: int = betterproto.uint32_field(3)
    owned: bool = betterproto.bool_field(4)
    event_level: int = betterproto.uint32_field(7)
    active_effects_mask: int = betterproto.uint64_field(12)
    wager_streak: int = betterproto.uint32_field(23)
    event_game_custom_actions: List["CMsgEventActionData"] = betterproto.message_field(
        25
    )
    tip_amount_index: int = betterproto.uint32_field(26)
    active_event_season_id: int = betterproto.uint32_field(27)
    teleport_fx_level: int = betterproto.uint32_field(28)
    networked_event_actions: List["CMsgEventActionData"] = betterproto.message_field(30)
    periodic_resources: List["CMsgPeriodicResourceData"] = betterproto.message_field(31)
    extra_event_messages: List["CExtraMsgBlock"] = betterproto.message_field(32)


@dataclass
class CMsgLobbyEventGameData(betterproto.Message):
    game_seed: int = betterproto.uint32_field(1)
    event_window_start_time: int = betterproto.uint32_field(2)


@dataclass
class CSODOTALobbyInvite(betterproto.Message):
    group_id: int = betterproto.uint64_field(1)
    sender_id: float = betterproto.fixed64_field(2)
    sender_name: str = betterproto.string_field(3)
    members: List["CSODOTALobbyInviteLobbyMember"] = betterproto.message_field(4)
    custom_game_id: int = betterproto.uint64_field(5)
    invite_gid: float = betterproto.fixed64_field(6)
    custom_game_crc: float = betterproto.fixed64_field(7)
    custom_game_timestamp: float = betterproto.fixed32_field(8)


@dataclass
class CSODOTALobbyInviteLobbyMember(betterproto.Message):
    name: str = betterproto.string_field(1)
    steam_id: float = betterproto.fixed64_field(2)


@dataclass
class CSODOTALobbyMember(betterproto.Message):
    id: float = betterproto.fixed64_field(1)
    hero_id: int = betterproto.int32_field(2)
    team: "DOTA_GC_TEAM" = betterproto.enum_field(3)
    slot: int = betterproto.uint32_field(7)
    leaver_status: "DOTALeaverStatusT" = betterproto.enum_field(16)
    leaver_actions: int = betterproto.uint32_field(28)
    coach_team: "DOTA_GC_TEAM" = betterproto.enum_field(23)
    custom_game_product_ids: List[int] = betterproto.uint32_field(31)
    live_spectator_team: "DOTA_GC_TEAM" = betterproto.enum_field(40)
    pending_awards: List["CMsgPendingEventAward"] = betterproto.message_field(44)
    pending_awards_on_victory: List[
        "CMsgPendingEventAward"
    ] = betterproto.message_field(45)
    reports_available: int = betterproto.uint32_field(52)
    live_spectator_account_id: int = betterproto.uint32_field(55)
    comms_reports_available: int = betterproto.uint32_field(56)


@dataclass
class CSODOTAServerLobbyMember(betterproto.Message):
    pass


@dataclass
class CSODOTAStaticLobbyMember(betterproto.Message):
    name: str = betterproto.string_field(1)
    party_id: int = betterproto.uint64_field(2)
    channel: int = betterproto.uint32_field(3)
    cameraman: bool = betterproto.bool_field(4)


@dataclass
class CSODOTAServerStaticLobbyMember(betterproto.Message):
    steam_id: float = betterproto.fixed64_field(1)
    rank_tier: int = betterproto.int32_field(3)
    leaderboard_rank: int = betterproto.int32_field(4)
    lane_selection_flags: int = betterproto.int32_field(5)
    rank_mmr_boost_type: "EDOTAMMRBoostType" = betterproto.enum_field(6)
    coach_rating: int = betterproto.int32_field(7)
    coached_account_ids: List[int] = betterproto.uint32_field(8)
    was_mvp_last_game: bool = betterproto.bool_field(9)
    can_earn_rewards: bool = betterproto.bool_field(10)
    is_plus_subscriber: bool = betterproto.bool_field(11)
    favorite_team_packed: int = betterproto.uint64_field(12)
    is_steam_china: bool = betterproto.bool_field(13)
    title: int = betterproto.uint32_field(14)
    guild_id: int = betterproto.uint32_field(15)
    disabled_random_hero_bits: List[float] = betterproto.fixed32_field(16)
    disabled_hero_id: List[int] = betterproto.int32_field(17)
    enabled_hero_id: List[int] = betterproto.int32_field(18)
    banned_hero_ids: List[int] = betterproto.int32_field(19)


@dataclass
class CLobbyTeamDetails(betterproto.Message):
    team_name: str = betterproto.string_field(1)
    team_tag: str = betterproto.string_field(3)
    team_id: int = betterproto.uint32_field(4)
    team_logo: int = betterproto.uint64_field(5)
    team_base_logo: int = betterproto.uint64_field(6)
    team_banner_logo: int = betterproto.uint64_field(7)
    team_complete: bool = betterproto.bool_field(8)
    rank: int = betterproto.uint32_field(15)
    rank_change: int = betterproto.sint32_field(16)
    is_home_team: bool = betterproto.bool_field(17)
    is_challenge_match: bool = betterproto.bool_field(18)
    challenge_match_token_account: int = betterproto.uint64_field(19)
    team_logo_url: str = betterproto.string_field(20)
    team_abbreviation: str = betterproto.string_field(21)


@dataclass
class CLobbyGuildDetails(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    guild_primary_color: int = betterproto.uint32_field(2)
    guild_secondary_color: int = betterproto.uint32_field(3)
    guild_pattern: int = betterproto.uint32_field(4)
    guild_logo: int = betterproto.uint64_field(5)
    guild_points: int = betterproto.uint32_field(6)
    guild_event: int = betterproto.uint32_field(7)
    guild_flags: int = betterproto.uint32_field(8)
    team_for_guild: "DOTA_GC_TEAM" = betterproto.enum_field(9)
    guild_tag: str = betterproto.string_field(10)
    guild_weekly_percentile: int = betterproto.uint32_field(11)


@dataclass
class CLobbyTimedRewardDetails(betterproto.Message):
    item_def_index: int = betterproto.uint32_field(2)
    is_supply_crate: bool = betterproto.bool_field(3)
    is_timed_drop: bool = betterproto.bool_field(4)
    account_id: int = betterproto.uint32_field(5)
    origin: int = betterproto.uint32_field(6)


@dataclass
class CLobbyBroadcastChannelInfo(betterproto.Message):
    channel_id: int = betterproto.uint32_field(1)
    country_code: str = betterproto.string_field(2)
    description: str = betterproto.string_field(3)
    language_code: str = betterproto.string_field(4)


@dataclass
class CLobbyGuildChallenge(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    challenge_instance_id: int = betterproto.uint32_field(3)
    challenge_parameter: int = betterproto.uint32_field(4)
    challenge_timestamp: int = betterproto.uint32_field(5)
    challenge_period_serial: int = betterproto.uint32_field(6)
    challenge_progress_at_start: int = betterproto.uint32_field(7)
    eligible_account_ids: List[int] = betterproto.uint32_field(8)


@dataclass
class CDOTALobbyMatchQualityData(betterproto.Message):
    overall_quality: int = betterproto.uint32_field(1)
    team_balance: int = betterproto.uint32_field(2)
    match_skill_range: int = betterproto.uint32_field(3)
    match_behavior: int = betterproto.uint32_field(4)


@dataclass
class CSODOTALobby(betterproto.Message):
    lobby_id: int = betterproto.uint64_field(1)
    all_members: List["CSODOTALobbyMember"] = betterproto.message_field(120)
    member_indices: List[int] = betterproto.uint32_field(121)
    left_member_indices: List[int] = betterproto.uint32_field(122)
    free_member_indices: List[int] = betterproto.uint32_field(123)
    leader_id: float = betterproto.fixed64_field(11)
    server_id: float = betterproto.fixed64_field(6)
    game_mode: int = betterproto.uint32_field(3)
    pending_invites: List[float] = betterproto.fixed64_field(10)
    state: "CSODOTALobbyState" = betterproto.enum_field(4)
    connect: str = betterproto.string_field(5)
    lobby_type: "CSODOTALobbyLobbyType" = betterproto.enum_field(12)
    allow_cheats: bool = betterproto.bool_field(13)
    fill_with_bots: bool = betterproto.bool_field(14)
    game_name: str = betterproto.string_field(16)
    team_details: List["CLobbyTeamDetails"] = betterproto.message_field(17)
    tournament_id: int = betterproto.uint32_field(19)
    tournament_game_id: int = betterproto.uint32_field(20)
    server_region: int = betterproto.uint32_field(21)
    game_state: "DOTA_GameState" = betterproto.enum_field(22)
    num_spectators: int = betterproto.uint32_field(23)
    matchgroup: int = betterproto.uint32_field(25)
    cm_pick: "DOTA_CM_PICK" = betterproto.enum_field(28)
    match_id: int = betterproto.uint64_field(30)
    allow_spectating: bool = betterproto.bool_field(31)
    bot_difficulty_radiant: "DOTABotDifficulty" = betterproto.enum_field(36)
    pass_key: str = betterproto.string_field(39)
    leagueid: int = betterproto.uint32_field(42)
    penalty_level_radiant: int = betterproto.uint32_field(43)
    penalty_level_dire: int = betterproto.uint32_field(44)
    series_type: int = betterproto.uint32_field(46)
    radiant_series_wins: int = betterproto.uint32_field(47)
    dire_series_wins: int = betterproto.uint32_field(48)
    allchat: bool = betterproto.bool_field(51)
    dota_tv_delay: "LobbyDotaTVDelay" = betterproto.enum_field(53)
    custom_game_mode: str = betterproto.string_field(54)
    custom_map_name: str = betterproto.string_field(55)
    custom_difficulty: int = betterproto.uint32_field(56)
    lan: bool = betterproto.bool_field(57)
    broadcast_channel_info: List[
        "CLobbyBroadcastChannelInfo"
    ] = betterproto.message_field(58)
    first_leaver_accountid: int = betterproto.uint32_field(59)
    series_id: int = betterproto.uint32_field(60)
    low_priority: bool = betterproto.bool_field(61)
    extra_messages: List["CSODOTALobbyCExtraMsg"] = betterproto.message_field(62)
    first_blood_happened: bool = betterproto.bool_field(65)
    match_outcome: "EMatchOutcome" = betterproto.enum_field(70)
    mass_disconnect: bool = betterproto.bool_field(67)
    custom_game_id: int = betterproto.uint64_field(68)
    custom_min_players: int = betterproto.uint32_field(71)
    custom_max_players: int = betterproto.uint32_field(72)
    visibility: "DOTALobbyVisibility" = betterproto.enum_field(75)
    custom_game_crc: float = betterproto.fixed64_field(76)
    custom_game_auto_created_lobby: bool = betterproto.bool_field(77)
    custom_game_timestamp: float = betterproto.fixed32_field(80)
    previous_series_matches: List[int] = betterproto.uint64_field(81)
    previous_match_override: int = betterproto.uint64_field(82)
    game_start_time: int = betterproto.uint32_field(87)
    pause_setting: "LobbyDotaPauseSetting" = betterproto.enum_field(88)
    weekend_tourney_division_id: int = betterproto.uint32_field(90)
    weekend_tourney_skill_level: int = betterproto.uint32_field(91)
    weekend_tourney_bracket_round: int = betterproto.uint32_field(92)
    bot_difficulty_dire: "DOTABotDifficulty" = betterproto.enum_field(93)
    bot_radiant: int = betterproto.uint64_field(94)
    bot_dire: int = betterproto.uint64_field(95)
    event_progression_enabled: List["EEvent"] = betterproto.enum_field(96)
    selection_priority_rules: "DOTASelectionPriorityRules" = betterproto.enum_field(97)
    series_previous_selection_priority_team_id: int = betterproto.uint32_field(98)
    series_current_selection_priority_team_id: int = betterproto.uint32_field(99)
    series_current_priority_team_choice: "DOTASelectionPriorityChoice" = (
        betterproto.enum_field(100)
    )
    series_current_non_priority_team_choice: "DOTASelectionPriorityChoice" = (
        betterproto.enum_field(101)
    )
    series_current_selection_priority_used_coin_toss: bool = betterproto.bool_field(102)
    current_primary_event: "EEvent" = betterproto.enum_field(103)
    emergency_disabled_hero_ids: List[int] = betterproto.int32_field(105)
    custom_game_private_key: float = betterproto.fixed64_field(106)
    custom_game_penalties: bool = betterproto.bool_field(107)
    lan_host_ping_location: str = betterproto.string_field(109)
    league_node_id: int = betterproto.uint32_field(110)
    match_duration: int = betterproto.uint32_field(111)
    league_phase: int = betterproto.uint32_field(113)
    experimental_gameplay_enabled: bool = betterproto.bool_field(116)
    guild_challenges: List["CLobbyGuildChallenge"] = betterproto.message_field(117)
    guild_details: List["CLobbyGuildDetails"] = betterproto.message_field(118)
    requested_hero_ids: List[int] = betterproto.int32_field(124)
    coach_friend_requests: List[
        "CMsgLobbyCoachFriendRequest"
    ] = betterproto.message_field(125)
    is_in_steam_china: bool = betterproto.bool_field(126)
    with_scenario_save: bool = betterproto.bool_field(127)
    lobby_creation_time: int = betterproto.uint32_field(128)
    event_game_definition: str = betterproto.string_field(129)
    match_quality_data: "CDOTALobbyMatchQualityData" = betterproto.message_field(131)


@dataclass
class CSODOTALobbyCExtraMsg(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    contents: bytes = betterproto.bytes_field(2)


@dataclass
class CSODOTAServerLobby(betterproto.Message):
    all_members: List["CSODOTAServerLobbyMember"] = betterproto.message_field(1)
    extra_startup_messages: List["CSODOTALobbyCExtraMsg"] = betterproto.message_field(2)


@dataclass
class CSODOTAStaticLobby(betterproto.Message):
    all_members: List["CSODOTAStaticLobbyMember"] = betterproto.message_field(1)
    is_player_draft: bool = betterproto.bool_field(2)
    is_last_match_in_series: bool = betterproto.bool_field(3)


@dataclass
class CSODOTAServerStaticLobby(betterproto.Message):
    all_members: List["CSODOTAServerStaticLobbyMember"] = betterproto.message_field(1)
    post_patch_strategy_time_buffer: float = betterproto.float_field(2)
    lobby_event_points: List["CMsgLobbyEventPoints"] = betterproto.message_field(3)


@dataclass
class CMsgAdditionalLobbyStartupAccountData(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    plus_data: "CMsgLobbyPlayerPlusSubscriptionData" = betterproto.message_field(2)
    unlocked_chat_wheel_message_ranges: List[
        "CMsgAdditionalLobbyStartupAccountDataChatWheelMessageRange"
    ] = betterproto.message_field(3)
    unlocked_ping_wheel_message_ranges: List[
        "CMsgAdditionalLobbyStartupAccountDataPingWheelMessageRange"
    ] = betterproto.message_field(4)


@dataclass
class CMsgAdditionalLobbyStartupAccountDataChatWheelMessageRange(betterproto.Message):
    message_id_start: int = betterproto.uint32_field(1)
    message_id_end: int = betterproto.uint32_field(2)


@dataclass
class CMsgAdditionalLobbyStartupAccountDataPingWheelMessageRange(betterproto.Message):
    message_id_start: int = betterproto.uint32_field(1)
    message_id_end: int = betterproto.uint32_field(2)


@dataclass
class CMsgLobbyInitializationComplete(betterproto.Message):
    pass


@dataclass
class CMsgLobbyPlaytestDetails(betterproto.Message):
    json: str = betterproto.string_field(1)


@dataclass
class CMsgLocalServerGuildData(betterproto.Message):
    guild_id: int = betterproto.uint32_field(1)
    event_id: "EEvent" = betterproto.enum_field(2)
    guild_points: int = betterproto.uint32_field(3)
    guild_logo: int = betterproto.uint64_field(4)
    guild_primary_color: int = betterproto.uint32_field(5)
    guild_secondary_color: int = betterproto.uint32_field(6)
    guild_pattern: int = betterproto.uint32_field(7)
    guild_flags: int = betterproto.uint32_field(8)
    guild_weekly_percentile: int = betterproto.uint32_field(9)


@dataclass
class CMsgLocalServerFakeLobbyData(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    event_points: List["CMsgLobbyEventPoints"] = betterproto.message_field(2)
    is_plus_subscriber: bool = betterproto.bool_field(3)
    primary_event_id: int = betterproto.uint32_field(4)
    favorite_team: int = betterproto.uint32_field(5)
    favorite_team_quality: int = betterproto.uint32_field(6)
    guild_info: "CMsgLocalServerGuildData" = betterproto.message_field(7)
    teleport_fx_level: int = betterproto.uint32_field(8)
    additional_data: "CMsgAdditionalLobbyStartupAccountData" = (
        betterproto.message_field(9)
    )
