# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_commonmessages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EPingSource(betterproto.Enum):
    k_ePingSource_Default = 0
    k_ePingSource_Warning = 1
    k_ePingSource_Wheel = 2
    k_ePingSource_System = 3


class EDOTAStatPopupTypes(betterproto.Enum):
    k_EDOTA_SPT_Textline = 0
    k_EDOTA_SPT_Basic = 1
    k_EDOTA_SPT_Poll = 2
    k_EDOTA_SPT_Grid = 3
    k_EDOTA_SPT_DualImage = 4
    k_EDOTA_SPT_Movie = 5


class DotaunitorderT(betterproto.Enum):
    DOTA_UNIT_ORDER_NONE = 0
    DOTA_UNIT_ORDER_MOVE_TO_POSITION = 1
    DOTA_UNIT_ORDER_MOVE_TO_TARGET = 2
    DOTA_UNIT_ORDER_ATTACK_MOVE = 3
    DOTA_UNIT_ORDER_ATTACK_TARGET = 4
    DOTA_UNIT_ORDER_CAST_POSITION = 5
    DOTA_UNIT_ORDER_CAST_TARGET = 6
    DOTA_UNIT_ORDER_CAST_TARGET_TREE = 7
    DOTA_UNIT_ORDER_CAST_NO_TARGET = 8
    DOTA_UNIT_ORDER_CAST_TOGGLE = 9
    DOTA_UNIT_ORDER_HOLD_POSITION = 10
    DOTA_UNIT_ORDER_TRAIN_ABILITY = 11
    DOTA_UNIT_ORDER_DROP_ITEM = 12
    DOTA_UNIT_ORDER_GIVE_ITEM = 13
    DOTA_UNIT_ORDER_PICKUP_ITEM = 14
    DOTA_UNIT_ORDER_PICKUP_RUNE = 15
    DOTA_UNIT_ORDER_PURCHASE_ITEM = 16
    DOTA_UNIT_ORDER_SELL_ITEM = 17
    DOTA_UNIT_ORDER_DISASSEMBLE_ITEM = 18
    DOTA_UNIT_ORDER_MOVE_ITEM = 19
    DOTA_UNIT_ORDER_CAST_TOGGLE_AUTO = 20
    DOTA_UNIT_ORDER_STOP = 21
    DOTA_UNIT_ORDER_TAUNT = 22
    DOTA_UNIT_ORDER_BUYBACK = 23
    DOTA_UNIT_ORDER_GLYPH = 24
    DOTA_UNIT_ORDER_EJECT_ITEM_FROM_STASH = 25
    DOTA_UNIT_ORDER_CAST_RUNE = 26
    DOTA_UNIT_ORDER_PING_ABILITY = 27
    DOTA_UNIT_ORDER_MOVE_TO_DIRECTION = 28
    DOTA_UNIT_ORDER_PATROL = 29
    DOTA_UNIT_ORDER_VECTOR_TARGET_POSITION = 30
    DOTA_UNIT_ORDER_RADAR = 31
    DOTA_UNIT_ORDER_SET_ITEM_COMBINE_LOCK = 32
    DOTA_UNIT_ORDER_CONTINUE = 33
    DOTA_UNIT_ORDER_VECTOR_TARGET_CANCELED = 34
    DOTA_UNIT_ORDER_CAST_RIVER_PAINT = 35
    DOTA_UNIT_ORDER_PREGAME_ADJUST_ITEM_ASSIGNMENT = 36
    DOTA_UNIT_ORDER_DROP_ITEM_AT_FOUNTAIN = 37
    DOTA_UNIT_ORDER_TAKE_ITEM_FROM_NEUTRAL_ITEM_STASH = 38
    DOTA_UNIT_ORDER_MOVE_RELATIVE = 39
    DOTA_UNIT_ORDER_CAST_TOGGLE_ALT = 40
    DOTA_UNIT_ORDER_CONSUME_ITEM = 41


class EDOTAVersusScenePlayerBehavior(betterproto.Enum):
    VS_PLAYER_BEHAVIOR_PLAY_ACTIVITY = 1
    VS_PLAYER_BEHAVIOR_CHAT_WHEEL = 2
    VS_PLAYER_BEHAVIOR_PLAYBACK_RATE = 3


@dataclass
class CDOTAMsg_LocationPing(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    target: int = betterproto.int32_field(3)
    direct_ping: bool = betterproto.bool_field(4)
    type: int = betterproto.uint32_field(5)
    ping_source: "EPingSource" = betterproto.enum_field(6)


@dataclass
class CDOTAMsg_ItemAlert(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    item_ability_id: int = betterproto.int32_field(3)


@dataclass
class CDOTAMsg_MapLine(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    initial: bool = betterproto.bool_field(3)


@dataclass
class CDOTAMsg_WorldLine(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    z: int = betterproto.int32_field(3)
    initial: bool = betterproto.bool_field(4)
    end: bool = betterproto.bool_field(5)


@dataclass
class CDOTAMsg_SendStatPopup(betterproto.Message):
    style: "EDOTAStatPopupTypes" = betterproto.enum_field(1)
    stat_strings: List[str] = betterproto.string_field(2)
    stat_images: List[int] = betterproto.int32_field(3)
    stat_image_types: List[int] = betterproto.int32_field(4)
    duration: float = betterproto.float_field(5)
    use_html: bool = betterproto.bool_field(6)
    movie_name: str = betterproto.string_field(7)


@dataclass
class CDOTAMsg_DismissAllStatPopups(betterproto.Message):
    time_delay: float = betterproto.float_field(1)


@dataclass
class CDOTAMsg_CoachHUDPing(betterproto.Message):
    x: int = betterproto.uint32_field(1)
    y: int = betterproto.uint32_field(2)
    tgtpath: str = betterproto.string_field(3)


@dataclass
class CDOTAMsg_UnitOrder(betterproto.Message):
    order_type: "DotaunitorderT" = betterproto.enum_field(2)
    units: List[int] = betterproto.int32_field(3)
    target_index: int = betterproto.int32_field(4)
    ability_index: int = betterproto.int32_field(5)
    position: "CMsgVector" = betterproto.message_field(6)
    sequence_number: int = betterproto.int32_field(8)
    flags: int = betterproto.uint32_field(9)


@dataclass
class VersusScene_PlayActivity(betterproto.Message):
    activities: List[
        "VersusScene_PlayActivityActivityInfo"
    ] = betterproto.message_field(1)
    playback_rate: float = betterproto.float_field(2)


@dataclass
class VersusScene_PlayActivityActivityInfo(betterproto.Message):
    activity: str = betterproto.string_field(1)
    disable_auto_kill: bool = betterproto.bool_field(2)
    force_looping: bool = betterproto.bool_field(3)


@dataclass
class VersusScene_ChatWheel(betterproto.Message):
    chat_message_id: int = betterproto.uint32_field(1)
    emoticon_id: int = betterproto.uint32_field(2)


@dataclass
class VersusScene_PlaybackRate(betterproto.Message):
    rate: float = betterproto.float_field(1)
