# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_showcase.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EShowcaseHeroPlusFlag(betterproto.Enum):
    k_eShowcaseHeroPlusFlag_None = 0
    k_eShowcaseHeroPlusFlag_BadgePosTop = 1
    k_eShowcaseHeroPlusFlag_BadgePosBottom = 2
    k_eShowcaseHeroPlusFlag_BadgePosLeft = 4
    k_eShowcaseHeroPlusFlag_BadgePosRight = 8
    k_eShowcaseHeroPlusFlag_ShowRelics = 16


class EShowcaseType(betterproto.Enum):
    k_eShowcaseType_Invalid = 0
    k_eShowcaseType_Profile = 1
    k_eShowcaseType_MiniProfile = 2
    k_eShowcaseType_DefaultProfile = 3
    k_eShowcaseType_DefaultMiniProfile = 4


class EShowcaseItemState(betterproto.Enum):
    k_eShowcaseItemState_Ok = 0
    k_eShowcaseItemState_MinorModifications = 1
    k_eShowcaseItemState_ValidityUnknown = 2
    k_eShowcaseItemState_PartiallyInvalid = 3
    k_eShowcaseItemState_Invalid = 4
    k_eShowcaseItemState_Failure = 5


class EShowcaseAuditAction(betterproto.Enum):
    k_eShowcaseAuditAction_Invalid = 0
    k_eShowcaseAuditAction_ShowcaseChanged = 1
    k_eShowcaseAuditAction_AdminShowcaseReset = 2
    k_eShowcaseAuditAction_AdminShowcaseAccountLocked = 3
    k_eShowcaseAuditAction_AdminShowcaseExonerated = 4
    k_eShowcaseAuditAction_AdminShowcaseConvicted = 5
    k_eShowcaseAuditAction_AdminModerationApproved = 6
    k_eShowcaseAuditAction_AdminModerationRejected = 7


class EShowcaseItemFlag(betterproto.Enum):
    k_eShowcaseItemFlag_None = 0
    k_eShowcaseItemFlag_FlipHorizontally = 1


class EShowcaseItemFlag_Hero(betterproto.Enum):
    k_eShowcaseItemFlag_Hero_None = 0
    k_eShowcaseItemFlag_Hero_ShowPedestal = 1
    k_eShowcaseItemFlag_Hero_UseCurrentLoadout = 2
    k_eShowcaseItemFlag_Hero_ShowHeroCard = 4
    k_eShowcaseItemFlag_Hero_HeroCardHideName = 8
    k_eShowcaseItemFlag_Hero_HeroCardUseMovie = 16


class CMsgShowcaseItem_PlayerMatchEPlayerOutcome(betterproto.Enum):
    k_eInvalid = 0
    k_eWin = 1
    k_eLoss = 2
    k_eNotScored = 3


class CMsgShowcaseEModerationState(betterproto.Enum):
    k_eModerationState_Ok = 0
    k_eModerationState_PendingApproval = 1


class CMsgClientToGCShowcaseGetUserDataResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eUnknownShowcase = 5


class CMsgClientToGCShowcaseSetUserDataResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalid = 5
    k_eLockedFromEditing = 6
    k_eBudgetExceeded = 7
    k_eCommunicationScoreTooLow = 8


class CMsgClientToGCShowcaseSubmitReportResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eAlreadyReported = 5


class CMsgClientToGCShowcaseAdminGetReportsRollupListResponseEResponse(
    betterproto.Enum
):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5


class CMsgClientToGCShowcaseAdminGetReportsRollupResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5
    k_eNotFound = 6


class CMsgClientToGCShowcaseAdminGetUserDetailsResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5


class CMsgClientToGCShowcaseAdminResetResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5


class CMsgClientToGCShowcaseAdminLockAccountResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5


class CMsgClientToGCShowcaseAdminConvictResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5
    k_eAlreadyConvicted = 6


class CMsgClientToGCShowcaseAdminExonerateResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5
    k_eAlreadyExonerated = 6


class CMsgClientToGCShowcaseModerationGetQueueResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5


class CMsgClientToGCShowcaseModerationApplyModerationResponseEResponse(
    betterproto.Enum
):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eNoPermission = 5
    k_eGone = 6


@dataclass
class CMsgShowcaseEconItemReference(betterproto.Message):
    id: int = betterproto.uint64_field(1)
    original_id: int = betterproto.uint64_field(2)
    definition_index: int = betterproto.uint32_field(3)
    equipment_slot_index: int = betterproto.int32_field(4)


@dataclass
class CMsgHeroPlusInfo(betterproto.Message):
    flags: int = betterproto.uint32_field(1)


@dataclass
class CMsgShowcaseItem_Trophy(betterproto.Message):
    data: "CMsgShowcaseItem_TrophyData" = betterproto.message_field(1)
    trophy_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgShowcaseItem_TrophyData(betterproto.Message):
    trophy_score: int = betterproto.uint32_field(1)


@dataclass
class CMsgShowcaseItem_EconItem(betterproto.Message):
    data: "CMsgShowcaseItem_EconItemData" = betterproto.message_field(1)
    ref: "CMsgShowcaseEconItemReference" = betterproto.message_field(2)


@dataclass
class CMsgShowcaseItem_EconItemData(betterproto.Message):
    econ_item: "CSOEconItem" = betterproto.message_field(1)


@dataclass
class CMsgShowcaseItem_Hero(betterproto.Message):
    data: "CMsgShowcaseItem_HeroData" = betterproto.message_field(1)
    hero_id: int = betterproto.int32_field(2)
    econ_item_refs: List["CMsgShowcaseEconItemReference"] = betterproto.message_field(3)
    rotation: int = betterproto.uint32_field(4)
    flags: int = betterproto.uint32_field(5)
    plus_info: "CMsgHeroPlusInfo" = betterproto.message_field(6)
    animation_name: str = betterproto.string_field(7)
    animation_playback_speed: int = betterproto.uint32_field(8)
    animation_offset: int = betterproto.uint32_field(9)
    zoom: int = betterproto.uint32_field(10)
    slot_index: int = betterproto.uint32_field(11)
    model_index: int = betterproto.uint32_field(12)


@dataclass
class CMsgShowcaseItem_HeroData(betterproto.Message):
    econ_items: List["CSOEconItem"] = betterproto.message_field(1)
    actual_hero_id: int = betterproto.int32_field(2)
    plus_hero_xp: int = betterproto.uint32_field(3)


@dataclass
class CMsgShowcaseItem_HeroIcon(betterproto.Message):
    data: "CMsgShowcaseItem_HeroIconData" = betterproto.message_field(1)
    hero_id: int = betterproto.int32_field(2)
    econ_item_ref: "CMsgShowcaseEconItemReference" = betterproto.message_field(3)


@dataclass
class CMsgShowcaseItem_HeroIconData(betterproto.Message):
    econ_item: "CSOEconItem" = betterproto.message_field(1)


@dataclass
class CMsgShowcaseItem_PlayerMatch(betterproto.Message):
    data: "CMsgShowcaseItem_PlayerMatchData" = betterproto.message_field(1)
    match_id: int = betterproto.uint64_field(2)
    player_slot: int = betterproto.uint32_field(3)


@dataclass
class CMsgShowcaseItem_PlayerMatchData(betterproto.Message):
    hero_id: int = betterproto.int32_field(1)
    timestamp: int = betterproto.uint32_field(2)
    duration: int = betterproto.uint32_field(3)
    game_mode: "DOTA_GameMode" = betterproto.enum_field(4)
    outcome: "CMsgShowcaseItem_PlayerMatchEPlayerOutcome" = betterproto.enum_field(5)
    kills: int = betterproto.uint32_field(6)
    deaths: int = betterproto.uint32_field(7)
    assists: int = betterproto.uint32_field(8)


@dataclass
class CMsgShowcaseItem_ChatWheel(betterproto.Message):
    data: "CMsgShowcaseItem_ChatWheelData" = betterproto.message_field(1)
    chat_wheel_message_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgShowcaseItem_ChatWheelData(betterproto.Message):
    pass


@dataclass
class CMsgShowcaseItem_Emoticon(betterproto.Message):
    data: "CMsgShowcaseItem_EmoticonData" = betterproto.message_field(1)
    emoticon_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgShowcaseItem_EmoticonData(betterproto.Message):
    pass


@dataclass
class CMsgShowcaseItem_SpiderGraph(betterproto.Message):
    data: "CMsgShowcaseItem_SpiderGraphData" = betterproto.message_field(1)


@dataclass
class CMsgShowcaseItem_SpiderGraphData(betterproto.Message):
    pass


@dataclass
class CMsgShowcaseItem_UserFeed(betterproto.Message):
    data: "CMsgShowcaseItem_UserFeedData" = betterproto.message_field(1)


@dataclass
class CMsgShowcaseItem_UserFeedData(betterproto.Message):
    pass


@dataclass
class CMsgShowcaseItem_Stat(betterproto.Message):
    data: "CMsgShowcaseItem_StatData" = betterproto.message_field(1)
    stat_id: "CMsgDOTAProfileCardEStatID" = betterproto.enum_field(2)


@dataclass
class CMsgShowcaseItem_StatData(betterproto.Message):
    stat_score: int = betterproto.uint32_field(1)


@dataclass
class CMsgShowcaseBackground(betterproto.Message):
    data: "CMsgShowcaseBackgroundData" = betterproto.message_field(1)
    loading_screen_ref: "CMsgShowcaseEconItemReference" = betterproto.message_field(2)
    dim: int = betterproto.uint32_field(3)
    blur: int = betterproto.uint32_field(4)
    background_id: int = betterproto.uint32_field(5)


@dataclass
class CMsgShowcaseBackgroundData(betterproto.Message):
    loading_screen: "CSOEconItem" = betterproto.message_field(1)


@dataclass
class CMsgShowcaseItemData(betterproto.Message):
    trophy: "CMsgShowcaseItem_Trophy" = betterproto.message_field(1, group="item")
    econ_item_icon: "CMsgShowcaseItem_EconItem" = betterproto.message_field(
        2, group="item"
    )
    sticker: "CMsgShowcaseItem_EconItem" = betterproto.message_field(3, group="item")
    hero_model: "CMsgShowcaseItem_Hero" = betterproto.message_field(4, group="item")
    player_match: "CMsgShowcaseItem_PlayerMatch" = betterproto.message_field(
        5, group="item"
    )
    chat_wheel: "CMsgShowcaseItem_ChatWheel" = betterproto.message_field(
        6, group="item"
    )
    spray: "CMsgShowcaseItem_ChatWheel" = betterproto.message_field(7, group="item")
    emoticon: "CMsgShowcaseItem_Emoticon" = betterproto.message_field(8, group="item")
    courier: "CMsgShowcaseItem_EconItem" = betterproto.message_field(10, group="item")
    ward: "CMsgShowcaseItem_EconItem" = betterproto.message_field(11, group="item")
    hero_icon: "CMsgShowcaseItem_HeroIcon" = betterproto.message_field(12, group="item")
    spider_graph: "CMsgShowcaseItem_SpiderGraph" = betterproto.message_field(
        13, group="item"
    )
    user_feed: "CMsgShowcaseItem_UserFeed" = betterproto.message_field(14, group="item")
    stat: "CMsgShowcaseItem_Stat" = betterproto.message_field(15, group="item")
    roshan: "CMsgShowcaseItem_EconItem" = betterproto.message_field(16, group="item")
    creep: "CMsgShowcaseItem_EconItem" = betterproto.message_field(17, group="item")
    tower: "CMsgShowcaseItem_EconItem" = betterproto.message_field(18, group="item")
    effigy: "CMsgShowcaseItem_EconItem" = betterproto.message_field(19, group="item")
    decoration: "CMsgShowcaseItem_EconItem" = betterproto.message_field(
        20, group="item"
    )
    background: "CMsgShowcaseBackground" = betterproto.message_field(100, group="item")


@dataclass
class CMsgShowcaseItemPosition(betterproto.Message):
    position_x: int = betterproto.int32_field(1)
    position_y: int = betterproto.int32_field(2)
    scale: int = betterproto.uint32_field(3)
    width: int = betterproto.uint32_field(4)
    height: int = betterproto.uint32_field(5)
    rotation: int = betterproto.uint32_field(6)
    parent_id: int = betterproto.uint32_field(7)
    parent_attachment_point_id: int = betterproto.uint32_field(8)
    attachment_anchor_x: int = betterproto.uint32_field(9)
    attachment_anchor_y: int = betterproto.uint32_field(10)


@dataclass
class CMsgShowcaseItem(betterproto.Message):
    showcase_item_id: int = betterproto.uint32_field(1)
    item_position: "CMsgShowcaseItemPosition" = betterproto.message_field(2)
    item_data: "CMsgShowcaseItemData" = betterproto.message_field(3)
    state: "EShowcaseItemState" = betterproto.enum_field(4)
    flags: int = betterproto.uint32_field(5)


@dataclass
class CMsgShowcase(betterproto.Message):
    showcase_items: List["CMsgShowcaseItem"] = betterproto.message_field(1)
    background: "CMsgShowcaseItem" = betterproto.message_field(3)
    moderation_state: "CMsgShowcaseEModerationState" = betterproto.enum_field(4)


@dataclass
class CMsgClientToGCShowcaseGetUserData(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)


@dataclass
class CMsgClientToGCShowcaseGetUserDataResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseGetUserDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    showcase: "CMsgShowcase" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCShowcaseSetUserData(betterproto.Message):
    showcase_type: "EShowcaseType" = betterproto.enum_field(1)
    showcase: "CMsgShowcase" = betterproto.message_field(2)
    format_version: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCShowcaseSetUserDataResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseSetUserDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    validated_showcase: "CMsgShowcase" = betterproto.message_field(2)
    locked_until_timestamp: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCShowcaseSubmitReport(betterproto.Message):
    target_account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)
    report_comment: str = betterproto.string_field(3)


@dataclass
class CMsgClientToGCShowcaseSubmitReportResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseSubmitReportResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgShowcaseReportsRollupInfo(betterproto.Message):
    rollup_id: int = betterproto.uint32_field(1)
    start_timestamp: int = betterproto.uint32_field(2)
    end_timestamp: int = betterproto.uint32_field(3)


@dataclass
class CMsgShowcaseReportsRollupList(betterproto.Message):
    rollups: List["CMsgShowcaseReportsRollupInfo"] = betterproto.message_field(1)


@dataclass
class CMsgShowcaseReportsRollupEntry(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)
    report_count: int = betterproto.uint32_field(3)


@dataclass
class CMsgShowcaseReportsRollup(betterproto.Message):
    rollup_info: "CMsgShowcaseReportsRollupInfo" = betterproto.message_field(1)
    rollup_entries: List["CMsgShowcaseReportsRollupEntry"] = betterproto.message_field(
        2
    )


@dataclass
class CMsgClientToGCShowcaseAdminGetReportsRollupList(betterproto.Message):
    pass


@dataclass
class CMsgClientToGCShowcaseAdminGetReportsRollupListResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminGetReportsRollupListResponseEResponse" = (
        betterproto.enum_field(1)
    )
    rollup_list: "CMsgShowcaseReportsRollupList" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminGetReportsRollup(betterproto.Message):
    rollup_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCShowcaseAdminGetReportsRollupResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminGetReportsRollupResponseEResponse" = (
        betterproto.enum_field(1)
    )
    rollup: "CMsgShowcaseReportsRollup" = betterproto.message_field(2)


@dataclass
class CMsgShowcaseAuditEntry(betterproto.Message):
    showcase_type: "EShowcaseType" = betterproto.enum_field(1)
    audit_action: "EShowcaseAuditAction" = betterproto.enum_field(2)
    audit_data: int = betterproto.uint64_field(3)
    timestamp: int = betterproto.uint32_field(4)


@dataclass
class CMsgShowcaseReport(betterproto.Message):
    reporter_account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)
    report_timestamp: int = betterproto.uint32_field(3)
    report_comment: str = betterproto.string_field(4)


@dataclass
class CMsgShowcaseAdminUserDetails(betterproto.Message):
    locked_until_timestamp: int = betterproto.uint32_field(1)
    audit_entries: List["CMsgShowcaseAuditEntry"] = betterproto.message_field(2)
    reports: List["CMsgShowcaseReport"] = betterproto.message_field(3)


@dataclass
class CMsgClientToGCShowcaseAdminGetUserDetails(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)


@dataclass
class CMsgClientToGCShowcaseAdminGetUserDetailsResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminGetUserDetailsResponseEResponse" = (
        betterproto.enum_field(1)
    )
    user_details: "CMsgShowcaseAdminUserDetails" = betterproto.message_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminReset(betterproto.Message):
    target_account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminResetResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminResetResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCShowcaseAdminLockAccount(betterproto.Message):
    target_account_id: int = betterproto.uint32_field(1)
    locked_until_timestamp: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminLockAccountResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminLockAccountResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCShowcaseAdminConvict(betterproto.Message):
    target_account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminConvictResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminConvictResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgClientToGCShowcaseAdminExonerate(betterproto.Message):
    target_account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)


@dataclass
class CMsgClientToGCShowcaseAdminExonerateResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseAdminExonerateResponseEResponse" = (
        betterproto.enum_field(1)
    )


@dataclass
class CMsgShowcaseModerationInfo(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)
    showcase_timestamp: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCShowcaseModerationGetQueue(betterproto.Message):
    start_timestamp: int = betterproto.uint32_field(1)
    result_count: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCShowcaseModerationGetQueueResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseModerationGetQueueResponseEResponse" = (
        betterproto.enum_field(1)
    )
    showcases: List["CMsgShowcaseModerationInfo"] = betterproto.message_field(2)


@dataclass
class CMsgClientToGCShowcaseModerationApplyModeration(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    showcase_type: "EShowcaseType" = betterproto.enum_field(2)
    showcase_timestamp: int = betterproto.uint32_field(3)
    approve: bool = betterproto.bool_field(4)


@dataclass
class CMsgClientToGCShowcaseModerationApplyModerationResponse(betterproto.Message):
    response: "CMsgClientToGCShowcaseModerationApplyModerationResponseEResponse" = (
        betterproto.enum_field(1)
    )
