# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_messages_mlbot.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class MLBot_MessageId(betterproto.Enum):
    mlbot_MatchMetadata = 1
    mlbot_TickBoundary = 2
    mlbot_TeamState_Radiant = 3
    mlbot_TeamState_Radiant_Delta = 4
    mlbot_TeamState_Dire = 5
    mlbot_TeamState_Dire_Delta = 6
    mlbot_PlayerCommand = 7
    mlbot_PlayerOrder = 8


@dataclass
class CMsgMLBotMatchMetadata(betterproto.Message):
    match_id: int = betterproto.uint64_field(1)
    lobby_id: int = betterproto.uint64_field(2)
    lobby_type: int = betterproto.int32_field(3)
    game_mode: int = betterproto.uint32_field(4)
    players: List["CMsgMLBotMatchMetadataPlayer"] = betterproto.message_field(5)


@dataclass
class CMsgMLBotMatchMetadataPlayer(betterproto.Message):
    player_id: int = betterproto.int32_field(1)
    team_id: int = betterproto.int32_field(2)
    hero_id: int = betterproto.int32_field(3)
    rank: int = betterproto.int32_field(4)


@dataclass
class CMsgMLBotTickBoundary(betterproto.Message):
    tick_number: int = betterproto.uint32_field(1)


@dataclass
class CMsgMLBot_PlayerOrder(betterproto.Message):
    player_id: int = betterproto.int32_field(1)
    team_id: int = betterproto.int32_field(2)
    order_type: int = betterproto.int32_field(3)
    selected_unit_handles: List[int] = betterproto.uint32_field(4)
    target_index: int = betterproto.int32_field(5)
    target_handle: int = betterproto.uint32_field(6)
    ability_index: int = betterproto.int32_field(7)
    ability_handle: int = betterproto.uint32_field(8)
    pos_x: float = betterproto.float_field(9)
    pos_y: float = betterproto.float_field(10)
    pos_z: float = betterproto.float_field(11)
    queue: bool = betterproto.bool_field(12)


@dataclass
class CMsgMLBot_TeamInference(betterproto.Message):
    team_id: int = betterproto.int32_field(1)
    bot_player_ids: List[int] = betterproto.int32_field(2)
    world_state: "CMsgBotWorldState" = betterproto.message_field(3)


@dataclass
class CMsgMLBot_TeamInferenceResponse(betterproto.Message):
    orders: List["CMsgMLBot_PlayerOrder"] = betterproto.message_field(1)


@dataclass
class CMsgMLBot_TeamInferenceList(betterproto.Message):
    messages: List["CMsgMLBot_TeamInference"] = betterproto.message_field(1)
