# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_gcmessages_client_bingo.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class CMsgClientToGCBingoGetUserDataResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4


class CMsgClientToGCBingoGetStatsDataResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4


class CMsgClientToGCBingoClaimRowResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eInvalidRow = 5
    k_eExpiredCard = 6


class CMsgClientToGCBingoDevRerollCardResponseEResponse(betterproto.Enum):
    k_eInternalError = 0
    k_eSuccess = 1
    k_eTooBusy = 2
    k_eDisabled = 3
    k_eTimeout = 4
    k_eExpiredCard = 6
    k_eNotAllowed = 7


@dataclass
class CMsgBingoSquare(betterproto.Message):
    stat_id: int = betterproto.uint32_field(1)
    stat_threshold: int = betterproto.int32_field(2)


@dataclass
class CMsgBingoUserData(betterproto.Message):
    squares: List["CMsgBingoSquare"] = betterproto.message_field(1)


@dataclass
class CMsgClientToGCBingoGetUserData(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    league_phase: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCBingoGetUserDataResponse(betterproto.Message):
    response: "CMsgClientToGCBingoGetUserDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    user_data: "CMsgBingoUserData" = betterproto.message_field(2)


@dataclass
class CMsgBingoIndividualStatData(betterproto.Message):
    stat_id: int = betterproto.uint32_field(1)
    stat_value: int = betterproto.int32_field(2)


@dataclass
class CMsgBingoStatsData(betterproto.Message):
    stats_data: List["CMsgBingoIndividualStatData"] = betterproto.message_field(1)


@dataclass
class CMsgClientToGCBingoGetStatsData(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    league_phase: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCBingoGetStatsDataResponse(betterproto.Message):
    response: "CMsgClientToGCBingoGetStatsDataResponseEResponse" = (
        betterproto.enum_field(1)
    )
    stats_data: "CMsgBingoStatsData" = betterproto.message_field(2)


@dataclass
class CMsgGCToClientBingoUserDataUpdated(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    league_phase: int = betterproto.uint32_field(2)
    user_data: "CMsgBingoUserData" = betterproto.message_field(3)


@dataclass
class CMsgClientToGCBingoClaimRow(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    league_phase: int = betterproto.uint32_field(2)
    row_index: int = betterproto.uint32_field(3)


@dataclass
class CMsgClientToGCBingoClaimRowResponse(betterproto.Message):
    response: "CMsgClientToGCBingoClaimRowResponseEResponse" = betterproto.enum_field(1)


@dataclass
class CMsgClientToGCBingoDevRerollCard(betterproto.Message):
    league_id: int = betterproto.uint32_field(1)
    league_phase: int = betterproto.uint32_field(2)


@dataclass
class CMsgClientToGCBingoDevRerollCardResponse(betterproto.Message):
    response: "CMsgClientToGCBingoDevRerollCardResponseEResponse" = (
        betterproto.enum_field(1)
    )
