# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: dota_fighting_game_p2p_messages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class CP2P_FightingGame_GameDataEState(betterproto.Enum):
    k_ChoosingCharacter = 1
    k_Loaded = 2
    k_Fighting = 3


@dataclass
class CMsgFightingGame_GameData_Fighting(betterproto.Message):
    last_acked_frame: int = betterproto.int32_field(1)
    player_id: int = betterproto.uint32_field(2)
    last_crc_frame: int = betterproto.int32_field(3)
    last_crc_value: int = betterproto.uint32_field(4)
    now: float = betterproto.float_field(5)
    peer_ack_time: float = betterproto.float_field(6)
    input_start_frame: int = betterproto.int32_field(7)
    input_sample: List[
        "CMsgFightingGame_GameData_FightingInputSample"
    ] = betterproto.message_field(8)


@dataclass
class CMsgFightingGame_GameData_FightingInputSample(betterproto.Message):
    button_mask: int = betterproto.uint32_field(1)


@dataclass
class CMsgFightingGame_GameData_CharacterSelect(betterproto.Message):
    cursor_index: int = betterproto.uint32_field(1)
    selected_hero_id: int = betterproto.int32_field(2)
    selected_style: int = betterproto.uint32_field(3)
    econ_item_refs: List[
        "CMsgFightingGame_GameData_CharacterSelectItem"
    ] = betterproto.message_field(4)
    message_ack: int = betterproto.int64_field(5)
    confirmed_style: bool = betterproto.bool_field(6)


@dataclass
class CMsgFightingGame_GameData_CharacterSelectItem(betterproto.Message):
    item_def: int = betterproto.uint32_field(1)
    style_index: int = betterproto.uint32_field(2)


@dataclass
class CMsgFightingGame_GameData_Loaded(betterproto.Message):
    now: float = betterproto.float_field(1)
    peer_ack_time: float = betterproto.float_field(2)
    proposed_start_time: float = betterproto.float_field(3)
    accepted_start_time: float = betterproto.float_field(4)


@dataclass
class CP2P_FightingGame_GameData(betterproto.Message):
    state: "CP2P_FightingGame_GameDataEState" = betterproto.enum_field(1)
    fight: "CMsgFightingGame_GameData_Fighting" = betterproto.message_field(
        2, group="state_data"
    )
    character_select: "CMsgFightingGame_GameData_CharacterSelect" = (
        betterproto.message_field(3, group="state_data")
    )
    loaded: "CMsgFightingGame_GameData_Loaded" = betterproto.message_field(
        4, group="state_data"
    )
