# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: steammessages_oauth.steamworkssdk.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto
import grpclib


@dataclass
class COAuthToken_ImplicitGrantNoPrompt_Request(betterproto.Message):
    clientid: str = betterproto.string_field(1)


@dataclass
class COAuthToken_ImplicitGrantNoPrompt_Response(betterproto.Message):
    access_token: str = betterproto.string_field(1)
    redirect_uri: str = betterproto.string_field(2)


class OAuthTokenStub(betterproto.ServiceStub):
    async def implicit_grant_no_prompt(
        self, *, clientid: str = ""
    ) -> COAuthToken_ImplicitGrantNoPrompt_Response:
        request = COAuthToken_ImplicitGrantNoPrompt_Request()
        request.clientid = clientid

        return await self._unary_unary(
            "/.OAuthToken/ImplicitGrantNoPrompt",
            request,
            COAuthToken_ImplicitGrantNoPrompt_Response,
        )
