# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: base_modifier.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class MODIFIER_ENTRY_TYPE(betterproto.Enum):
    MODIFIER_ENTRY_TYPE_ACTIVE = 1
    MODIFIER_ENTRY_TYPE_REMOVED = 2


@dataclass
class CModifierTableEntry(betterproto.Message):
    entry_type: "MODIFIER_ENTRY_TYPE" = betterproto.enum_field(1)
    parent: int = betterproto.uint32_field(2)
    serial_number: int = betterproto.uint32_field(3)
    modifier_subclass: int = betterproto.uint32_field(4)
    stack_count: int = betterproto.int32_field(5)
    max_stack_count: int = betterproto.int32_field(6)
    last_applied_time: float = betterproto.float_field(7)
    duration: float = betterproto.float_field(8)
    caster: int = betterproto.uint32_field(9)
    ability: int = betterproto.uint32_field(10)
    aura_provider_serial_number: int = betterproto.int32_field(11)
    aura_provider_ehandle: int = betterproto.uint32_field(12)
    ability_subclass: int = betterproto.uint32_field(13)
    bool1_: bool = betterproto.bool_field(20)
    bool2_: bool = betterproto.bool_field(21)
    bool3_: bool = betterproto.bool_field(22)
    bool4_: bool = betterproto.bool_field(23)
    int1_: int = betterproto.int32_field(25)
    int2_: int = betterproto.int32_field(26)
    int3_: int = betterproto.int32_field(27)
    int4_: int = betterproto.int32_field(28)
    float1_: float = betterproto.float_field(30)
    float2_: float = betterproto.float_field(31)
    float3_: float = betterproto.float_field(32)
    float4_: float = betterproto.float_field(33)
    float5_: float = betterproto.float_field(49)
    float6_: float = betterproto.float_field(50)
    float7_: float = betterproto.float_field(51)
    float8_: float = betterproto.float_field(52)
    float9_: float = betterproto.float_field(53)
    float10_: float = betterproto.float_field(54)
    uint1_: int = betterproto.uint64_field(35)
    uint2_: int = betterproto.uint64_field(36)
    uint3_: int = betterproto.uint64_field(37)
    uint4_: int = betterproto.uint64_field(38)
    vec1_: "CMsgVector" = betterproto.message_field(40)
    vec2_: "CMsgVector" = betterproto.message_field(41)
    vec3_: "CMsgVector" = betterproto.message_field(42)
    vec4_: "CMsgVector" = betterproto.message_field(43)
    string1_: str = betterproto.string_field(45)
    string2_: str = betterproto.string_field(46)
    string3_: str = betterproto.string_field(47)
    string4_: str = betterproto.string_field(48)
