# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: citadel_gcmessages_common.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class CMsgLaneColor(betterproto.Enum):
    k_ELaneColor_Invalid = 0
    k_ELaneColor_Yellow = 1
    k_ELaneColor_Green = 3
    k_ELaneColor_Blue = 4
    k_ELaneColor_Purple = 6


class EGCCitadelCommonMessages(betterproto.Enum):
    k_EMsgAnyToGCReportAsserts = 7000
    k_EMsgAnyToGCReportAssertsResponse = 7001


class ECitadelMatchMode(betterproto.Enum):
    k_ECitadelMatchMode_Invalid = 0
    k_ECitadelMatchMode_Unranked = 1
    k_ECitadelMatchMode_PrivateLobby = 2
    k_ECitadelMatchMode_CoopBot = 3
    k_ECitadelMatchMode_Ranked = 4
    k_ECitadelMatchMode_ServerTest = 5
    k_ECitadelMatchMode_Tutorial = 6


class ECitadelLobbyTeam(betterproto.Enum):
    k_ECitadelLobbyTeam_Team0 = 0
    k_ECitadelLobbyTeam_Team1 = 1
    k_ECitadelLobbyTeam_Spectator = 16


class ECitadelAccountStatMedal(betterproto.Enum):
    k_eNone = 0
    k_eBronze = 1
    k_eSilver = 2
    k_eGold = 3


class ECitadelObjective(betterproto.Enum):
    k_eCitadelObjective_Team0_Core = 0
    k_eCitadelObjective_Team0_Tier1_Lane1 = 1
    k_eCitadelObjective_Team0_Tier1_Lane2 = 2
    k_eCitadelObjective_Team0_Tier1_Lane3 = 3
    k_eCitadelObjective_Team0_Tier1_Lane4 = 4
    k_eCitadelObjective_Team0_Tier2_Lane1 = 5
    k_eCitadelObjective_Team0_Tier2_Lane2 = 6
    k_eCitadelObjective_Team0_Tier2_Lane3 = 7
    k_eCitadelObjective_Team0_Tier2_Lane4 = 8
    k_eCitadelObjective_Team0_Titan = 9
    k_eCitadelObjective_Team0_TitanShieldGenerator_1 = 10
    k_eCitadelObjective_Team0_TitanShieldGenerator_2 = 11
    k_eCitadelObjective_Team0_BarrackBoss_Lane1 = 12
    k_eCitadelObjective_Team0_BarrackBoss_Lane2 = 13
    k_eCitadelObjective_Team0_BarrackBoss_Lane3 = 14
    k_eCitadelObjective_Team0_BarrackBoss_Lane4 = 15
    k_eCitadelObjective_Team1_Core = 16
    k_eCitadelObjective_Team1_Tier1_Lane1 = 17
    k_eCitadelObjective_Team1_Tier1_Lane2 = 18
    k_eCitadelObjective_Team1_Tier1_Lane3 = 19
    k_eCitadelObjective_Team1_Tier1_Lane4 = 20
    k_eCitadelObjective_Team1_Tier2_Lane1 = 21
    k_eCitadelObjective_Team1_Tier2_Lane2 = 22
    k_eCitadelObjective_Team1_Tier2_Lane3 = 23
    k_eCitadelObjective_Team1_Tier2_Lane4 = 24
    k_eCitadelObjective_Team1_Titan = 25
    k_eCitadelObjective_Team1_TitanShieldGenerator_1 = 26
    k_eCitadelObjective_Team1_TitanShieldGenerator_2 = 27
    k_eCitadelObjective_Team1_BarrackBoss_Lane1 = 28
    k_eCitadelObjective_Team1_BarrackBoss_Lane2 = 29
    k_eCitadelObjective_Team1_BarrackBoss_Lane3 = 30
    k_eCitadelObjective_Team1_BarrackBoss_Lane4 = 31
    k_eCitadelObjective_Neutral_Mid = 32


class ECitadelTeamObjective(betterproto.Enum):
    k_eCitadelTeamObjective_Core = 0
    k_eCitadelTeamObjective_Tier1_Lane1 = 1
    k_eCitadelTeamObjective_Tier1_Lane2 = 2
    k_eCitadelTeamObjective_Tier1_Lane3 = 3
    k_eCitadelTeamObjective_Tier1_Lane4 = 4
    k_eCitadelTeamObjective_Tier2_Lane1 = 5
    k_eCitadelTeamObjective_Tier2_Lane2 = 6
    k_eCitadelTeamObjective_Tier2_Lane3 = 7
    k_eCitadelTeamObjective_Tier2_Lane4 = 8
    k_eCitadelTeamObjective_Titan = 9
    k_eCitadelTeamObjective_TitanShieldGenerator_1 = 10
    k_eCitadelTeamObjective_TitanShieldGenerator_2 = 11
    k_eCitadelTeamObjective_BarrackBoss_Lane1 = 12
    k_eCitadelTeamObjective_BarrackBoss_Lane2 = 13
    k_eCitadelTeamObjective_BarrackBoss_Lane3 = 14
    k_eCitadelTeamObjective_BarrackBoss_Lane4 = 15


class ECitadelBotDifficulty(betterproto.Enum):
    k_ECitadelBotDifficulty_None = 0
    k_ECitadelBotDifficulty_Easy = 1
    k_ECitadelBotDifficulty_Medium = 2
    k_ECitadelBotDifficulty_Hard = 3
    k_ECitadelBotDifficulty_Nightmare = 4
    k_ECitadelBotDifficulty_Guided = 5


class ECitadelRegionMode(betterproto.Enum):
    k_ECitadelRegionMode_ROW = 0
    k_ECitadelRegionMode_Europe = 1
    k_ECitadelRegionMode_SEAsia = 2
    k_ECitadelRegionMode_SAmerica = 3
    k_ECitadelRegionMode_Russia = 4
    k_ECitadelRegionMode_Oceania = 5


class ECitadelGameMode(betterproto.Enum):
    k_ECitadelGameMode_Invalid = 0
    k_ECitadelGameMode_Normal = 1
    k_ECitadelGameMode_1v1Test = 2
    k_ECitadelGameMode_Sandbox = 3


class ELobbyServerState(betterproto.Enum):
    k_eLobbyServerState_Assign = 0
    k_eLobbyServerState_InGame = 1
    k_eLobbyServerState_PostMatch = 2
    k_eLobbyServerState_SignedOut = 3
    k_eLobbyServerState_Abandoned = 4


class EBannedFeature(betterproto.Enum):
    k_eBannedFeature_Invalid = 0
    k_eBannedFeature_LowPriorityMatchmaking = 1
    k_eBannedFeature_CommsRestricted = 2


class EFeatureBanReason(betterproto.Enum):
    k_eFeatureBanReason_Invalid = 0
    k_eFeatureBanReason_DevCommand = 1
    k_eFeatureBanReason_PlayerReports = 2
    k_eFeatureBanReason_MatchAbandons = 3


class CSOCitadelPartyEMemberRights(betterproto.Enum):
    k_eMemberRights_Admin = 1
    k_eMemberRights_Creator = 2


class CSOCitadelPartyEPlayerType(betterproto.Enum):
    k_ePlayerType_Player = 0
    k_ePlayerType_Spectator = 1


class CSOCitadelPartyEChatMode(betterproto.Enum):
    k_eNone = 0
    k_ePartyChat = 1
    k_eTeamChat = 2


class CMsgMatchPlayerDamageMatrixEStatType(betterproto.Enum):
    k_eType_Damage = 0
    k_eType_Healing = 1
    k_eType_HealPrevented = 2
    k_eType_Mitigated = 3
    k_eType_LethalDamage = 4


class CMsgMatchMetaDataContentsEMatchOutcome(betterproto.Enum):
    k_eOutcome_TeamWin = 0
    k_eOutcome_Error = 1


class CMsgMatchMetaDataContentsEGoldSource(betterproto.Enum):
    k_ePlayers = 1
    k_eLaneCreeps = 2
    k_eNeutrals = 3
    k_eBosses = 4
    k_eTreasure = 5
    k_eAssists = 6
    k_eDenies = 7


@dataclass
class CSOCitadelLobby(betterproto.Message):
    lobby_id: int = betterproto.uint64_field(1)
    match_id: int = betterproto.uint64_field(2)
    match_mode: "ECitadelMatchMode" = betterproto.enum_field(3)
    game_mode: "ECitadelGameMode" = betterproto.enum_field(4)
    compatibility_version: int = betterproto.uint32_field(5)
    extra_messages: List["CExtraMsgBlock"] = betterproto.message_field(6)
    server_steam_id: float = betterproto.fixed64_field(7)
    server_state: "ELobbyServerState" = betterproto.enum_field(8)
    udp_connect_ip: int = betterproto.uint32_field(9)
    udp_connect_port: int = betterproto.uint32_field(10)
    sdr_address: bytes = betterproto.bytes_field(12)
    server_version: int = betterproto.uint32_field(13)
    safe_to_abandon: bool = betterproto.bool_field(14)


@dataclass
class CLobbyData_PostMatchSurvey(betterproto.Message):
    surveys: List["CLobbyData_PostMatchSurveyPlayerSurvey"] = betterproto.message_field(
        1
    )


@dataclass
class CLobbyData_PostMatchSurveyPlayerSurvey(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    question_id: int = betterproto.uint32_field(2)


@dataclass
class CMsgHeroSelectionMatchInfo(betterproto.Message):
    hero_selections: List["CMsgHeroSelectionMatchInfoHero"] = betterproto.message_field(
        1
    )


@dataclass
class CMsgHeroSelectionMatchInfoHero(betterproto.Message):
    hero_id: int = betterproto.uint32_field(1)
    priority: int = betterproto.uint32_field(2)


@dataclass
class CMsgStartFindingMatchInfo(betterproto.Message):
    server_search_key: str = betterproto.string_field(1)
    server_command_string: str = betterproto.string_field(2)
    match_mode: "ECitadelMatchMode" = betterproto.enum_field(3)
    game_mode: "ECitadelGameMode" = betterproto.enum_field(5)
    solo_match: bool = betterproto.bool_field(6)
    bot_difficulty: "ECitadelBotDifficulty" = betterproto.enum_field(7)
    region_mode: "ECitadelRegionMode" = betterproto.enum_field(8)


@dataclass
class CMsgAnyToGCReportAsserts(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    asserts: List["CMsgAnyToGCReportAssertsTrackedAssert"] = betterproto.message_field(
        2
    )


@dataclass
class CMsgAnyToGCReportAssertsTrackedAssert(betterproto.Message):
    filename: str = betterproto.string_field(1)
    line_number: int = betterproto.uint32_field(2)
    sample_msg: str = betterproto.string_field(3)
    sample_stack: str = betterproto.string_field(4)
    times_fired: int = betterproto.uint32_field(5)
    function_name: str = betterproto.string_field(6)
    condition: str = betterproto.string_field(7)
    total_times_fired: int = betterproto.uint32_field(8)


@dataclass
class CMsgAnyToGCReportAssertsResponse(betterproto.Message):
    success: bool = betterproto.bool_field(1)


@dataclass
class CMsgRegionPingTimesClient(betterproto.Message):
    data_center_codes: List[float] = betterproto.fixed32_field(1)
    ping_times: List[int] = betterproto.uint32_field(2)


@dataclass
class CSOCitadelParty(betterproto.Message):
    party_id: int = betterproto.uint64_field(1)
    members: List["CSOCitadelPartyMember"] = betterproto.message_field(2)
    invites: List["CSOCitadelPartyInvite"] = betterproto.message_field(3)
    dev_server_command: str = betterproto.string_field(4)
    left_members: List["CSOCitadelPartyLeftMember"] = betterproto.message_field(5)
    join_code: int = betterproto.uint64_field(6)
    bot_difficulty: "ECitadelBotDifficulty" = betterproto.enum_field(7)
    match_mode: "ECitadelMatchMode" = betterproto.enum_field(9)
    game_mode: "ECitadelGameMode" = betterproto.enum_field(10)
    match_making_start_time: int = betterproto.uint32_field(11)
    server_search_key: str = betterproto.string_field(12)
    is_high_skill_range_party: bool = betterproto.bool_field(13)
    chat_mode: "CSOCitadelPartyEChatMode" = betterproto.enum_field(14)
    region_mode: "ECitadelRegionMode" = betterproto.enum_field(15)
    is_private_lobby: bool = betterproto.bool_field(16)
    private_lobby_settings: "CSOCitadelPartyPrivateLobbySettings" = (
        betterproto.message_field(17)
    )


@dataclass
class CSOCitadelPartyPrivateLobbySlot(betterproto.Message):
    slot_id: int = betterproto.uint32_field(1)
    player_account_id: int = betterproto.uint32_field(2)


@dataclass
class CSOCitadelPartyServerRegion(betterproto.Message):
    region_id: int = betterproto.uint32_field(1)


@dataclass
class CSOCitadelPartyPrivateLobbySettings(betterproto.Message):
    min_roster_size: int = betterproto.uint32_field(1)
    match_slots: List["CSOCitadelPartyPrivateLobbySlot"] = betterproto.message_field(2)
    randomize_lanes: bool = betterproto.bool_field(3)
    server_region: int = betterproto.uint32_field(4)
    is_publicly_visible: bool = betterproto.bool_field(6)
    cheats_enabled: bool = betterproto.bool_field(7)
    available_regions: List["CSOCitadelPartyServerRegion"] = betterproto.message_field(
        8
    )


@dataclass
class CSOCitadelPartyMember(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    persona_name: str = betterproto.string_field(2)
    rights_flags: int = betterproto.uint32_field(3)
    is_ready: bool = betterproto.bool_field(4)
    player_type: "CSOCitadelPartyEPlayerType" = betterproto.enum_field(5)
    compatibility_version: int = betterproto.uint32_field(6)
    platform: "EGCPlatform" = betterproto.enum_field(7)
    team: int = betterproto.uint32_field(8)
    hero_roster: "CMsgHeroSelectionMatchInfo" = betterproto.message_field(9)
    permissions: int = betterproto.uint64_field(10)
    new_player_progress: int = betterproto.uint64_field(11)
    owned_heroes: List[int] = betterproto.uint32_field(12)


@dataclass
class CSOCitadelPartyLeftMember(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    rights_flags: int = betterproto.uint32_field(2)
    player_type: "CSOCitadelPartyEPlayerType" = betterproto.enum_field(3)


@dataclass
class CSOCitadelPartyInvite(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    persona_name: str = betterproto.string_field(2)
    invited_by: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchPlayerPathsData(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    interval_s: float = betterproto.float_field(2)
    x_resolution: int = betterproto.uint32_field(3)
    y_resolution: int = betterproto.uint32_field(4)
    paths: List["CMsgMatchPlayerPathsDataPath"] = betterproto.message_field(5)


@dataclass
class CMsgMatchPlayerPathsDataPath(betterproto.Message):
    player_slot: int = betterproto.uint32_field(1)
    x_min: float = betterproto.float_field(2)
    y_min: float = betterproto.float_field(3)
    x_max: float = betterproto.float_field(4)
    y_max: float = betterproto.float_field(5)
    x_pos: List[int] = betterproto.uint32_field(6)
    y_pos: List[int] = betterproto.uint32_field(7)
    alive: List[bool] = betterproto.bool_field(8)
    health: List[int] = betterproto.uint32_field(9)


@dataclass
class CMsgMatchPlayerDamageMatrix(betterproto.Message):
    damage_dealers: List[
        "CMsgMatchPlayerDamageMatrixDamageDealer"
    ] = betterproto.message_field(1)
    sample_time_s: List[int] = betterproto.uint32_field(2)
    source_details: "CMsgMatchPlayerDamageMatrixSourceDetails" = (
        betterproto.message_field(3)
    )


@dataclass
class CMsgMatchPlayerDamageMatrixDamageToPlayer(betterproto.Message):
    target_player_slot: int = betterproto.uint32_field(1)
    damage: List[int] = betterproto.uint32_field(2)


@dataclass
class CMsgMatchPlayerDamageMatrixDamageSource(betterproto.Message):
    damage_to_players: List[
        "CMsgMatchPlayerDamageMatrixDamageToPlayer"
    ] = betterproto.message_field(2)
    source_details_index: int = betterproto.uint32_field(4)


@dataclass
class CMsgMatchPlayerDamageMatrixDamageDealer(betterproto.Message):
    dealer_player_slot: int = betterproto.uint32_field(1)
    damage_sources: List[
        "CMsgMatchPlayerDamageMatrixDamageSource"
    ] = betterproto.message_field(2)


@dataclass
class CMsgMatchPlayerDamageMatrixSourceDetails(betterproto.Message):
    stat_type: List["CMsgMatchPlayerDamageMatrixEStatType"] = betterproto.enum_field(1)
    source_name: List[str] = betterproto.string_field(2)


@dataclass
class CMsgMatchMetaDataContents(betterproto.Message):
    match_info: "CMsgMatchMetaDataContentsMatchInfo" = betterproto.message_field(2)


@dataclass
class CMsgMatchMetaDataContentsPosition(betterproto.Message):
    x: float = betterproto.float_field(1)
    y: float = betterproto.float_field(2)
    z: float = betterproto.float_field(3)


@dataclass
class CMsgMatchMetaDataContentsDeaths(betterproto.Message):
    game_time_s: int = betterproto.uint32_field(1)
    killer_player_slot: int = betterproto.uint32_field(9)
    death_pos: "CMsgMatchMetaDataContentsPosition" = betterproto.message_field(10)
    killer_pos: "CMsgMatchMetaDataContentsPosition" = betterproto.message_field(11)
    death_duration_s: int = betterproto.uint32_field(12)


@dataclass
class CMsgMatchMetaDataContentsItems(betterproto.Message):
    game_time_s: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint32_field(2)
    upgrade_id: int = betterproto.uint32_field(3)
    sold_time_s: int = betterproto.uint32_field(4)
    flags: int = betterproto.uint32_field(5)
    imbued_ability_id: int = betterproto.uint32_field(6)


@dataclass
class CMsgMatchMetaDataContentsPing(betterproto.Message):
    ping_type: int = betterproto.uint32_field(1)
    ping_data: int = betterproto.uint32_field(2)
    game_time_s: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchMetaDataContentsGoldSource(betterproto.Message):
    source: "CMsgMatchMetaDataContentsEGoldSource" = betterproto.enum_field(1)
    kills: int = betterproto.uint32_field(2)
    damage: int = betterproto.uint32_field(3)
    gold: int = betterproto.uint32_field(4)
    gold_orbs: int = betterproto.uint32_field(5)


@dataclass
class CMsgMatchMetaDataContentsCustomUserStatInfo(betterproto.Message):
    name: str = betterproto.string_field(1)
    id: int = betterproto.uint32_field(2)


@dataclass
class CMsgMatchMetaDataContentsCustomUserStat(betterproto.Message):
    value: int = betterproto.uint32_field(2)
    id: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchMetaDataContentsPlayerStats(betterproto.Message):
    time_stamp_s: int = betterproto.uint32_field(1)
    net_worth: int = betterproto.uint32_field(2)
    gold_player: int = betterproto.uint32_field(3)
    gold_player_orbs: int = betterproto.uint32_field(4)
    gold_lane_creep_orbs: int = betterproto.uint32_field(5)
    gold_neutral_creep_orbs: int = betterproto.uint32_field(6)
    gold_boss: int = betterproto.uint32_field(7)
    gold_boss_orb: int = betterproto.uint32_field(8)
    gold_treasure: int = betterproto.uint32_field(9)
    gold_denied: int = betterproto.uint32_field(10)
    gold_death_loss: int = betterproto.uint32_field(11)
    gold_lane_creep: int = betterproto.uint32_field(12)
    gold_neutral_creep: int = betterproto.uint32_field(13)
    kills: int = betterproto.uint32_field(14)
    deaths: int = betterproto.uint32_field(15)
    assists: int = betterproto.uint32_field(16)
    creep_kills: int = betterproto.uint32_field(17)
    neutral_kills: int = betterproto.uint32_field(18)
    possible_creeps: int = betterproto.uint32_field(19)
    creep_damage: int = betterproto.uint32_field(20)
    player_damage: int = betterproto.uint32_field(21)
    neutral_damage: int = betterproto.uint32_field(22)
    boss_damage: int = betterproto.uint32_field(23)
    denies: int = betterproto.uint32_field(24)
    player_healing: int = betterproto.uint32_field(25)
    ability_points: int = betterproto.uint32_field(26)
    self_healing: int = betterproto.uint32_field(27)
    player_damage_taken: int = betterproto.uint32_field(28)
    max_health: int = betterproto.uint32_field(29)
    weapon_power: int = betterproto.uint32_field(30)
    tech_power: int = betterproto.uint32_field(31)
    shots_hit: int = betterproto.uint32_field(32)
    shots_missed: int = betterproto.uint32_field(33)
    damage_absorbed: int = betterproto.uint32_field(34)
    absorption_provided: int = betterproto.uint32_field(35)
    hero_bullets_hit: int = betterproto.uint32_field(36)
    hero_bullets_hit_crit: int = betterproto.uint32_field(37)
    heal_prevented: int = betterproto.uint32_field(38)
    heal_lost: int = betterproto.uint32_field(39)
    gold_sources: List[
        "CMsgMatchMetaDataContentsGoldSource"
    ] = betterproto.message_field(40)
    custom_user_stats: List[
        "CMsgMatchMetaDataContentsCustomUserStat"
    ] = betterproto.message_field(41)
    damage_mitigated: int = betterproto.uint32_field(42)
    level: int = betterproto.uint32_field(43)


@dataclass
class CMsgMatchMetaDataContentsAbilityStat(betterproto.Message):
    ability_id: int = betterproto.uint32_field(1)
    ability_value: int = betterproto.uint32_field(2)


@dataclass
class CMsgMatchMetaDataContentsBookReward(betterproto.Message):
    book_id: int = betterproto.uint32_field(1)
    xp_amount: int = betterproto.uint32_field(2)
    starting_xp: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchMetaDataContentsPlayers(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    player_slot: int = betterproto.uint32_field(2)
    death_details: List["CMsgMatchMetaDataContentsDeaths"] = betterproto.message_field(
        3
    )
    items: List["CMsgMatchMetaDataContentsItems"] = betterproto.message_field(4)
    stats: List["CMsgMatchMetaDataContentsPlayerStats"] = betterproto.message_field(5)
    team: "ECitadelLobbyTeam" = betterproto.enum_field(6)
    kills: int = betterproto.uint32_field(8)
    deaths: int = betterproto.uint32_field(9)
    assists: int = betterproto.uint32_field(10)
    net_worth: int = betterproto.uint32_field(11)
    hero_id: int = betterproto.uint32_field(12)
    last_hits: int = betterproto.uint32_field(13)
    denies: int = betterproto.uint32_field(14)
    ability_points: int = betterproto.uint32_field(15)
    party: int = betterproto.uint32_field(16)
    assigned_lane: int = betterproto.uint32_field(17)
    level: int = betterproto.uint32_field(18)
    pings: List["CMsgMatchMetaDataContentsPing"] = betterproto.message_field(19)
    ability_stats: List[
        "CMsgMatchMetaDataContentsAbilityStat"
    ] = betterproto.message_field(20)
    stats_type_stat: List[float] = betterproto.float_field(21)
    book_rewards: List[
        "CMsgMatchMetaDataContentsBookReward"
    ] = betterproto.message_field(22)
    abandon_match_time_s: int = betterproto.uint32_field(23)


@dataclass
class CMsgMatchMetaDataContentsObjective(betterproto.Message):
    legacy_objective_id: "ECitadelObjective" = betterproto.enum_field(1)
    destroyed_time_s: int = betterproto.uint32_field(2)
    creep_damage: int = betterproto.uint32_field(4)
    creep_damage_mitigated: int = betterproto.uint32_field(5)
    player_damage: int = betterproto.uint32_field(6)
    player_damage_mitigated: int = betterproto.uint32_field(7)
    first_damage_time_s: int = betterproto.uint32_field(8)
    team_objective_id: "ECitadelTeamObjective" = betterproto.enum_field(9)
    team: "ECitadelLobbyTeam" = betterproto.enum_field(10)


@dataclass
class CMsgMatchMetaDataContentsMidBoss(betterproto.Message):
    team_killed: "ECitadelLobbyTeam" = betterproto.enum_field(1)
    team_claimed: "ECitadelLobbyTeam" = betterproto.enum_field(2)
    destroyed_time_s: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchMetaDataContentsPause(betterproto.Message):
    game_time_s: int = betterproto.uint32_field(1)
    pause_duration_s: int = betterproto.uint32_field(2)
    player_slot: int = betterproto.uint32_field(3)


@dataclass
class CMsgMatchMetaDataContentsWatchedDeathReplay(betterproto.Message):
    game_time_s: int = betterproto.uint32_field(1)
    player_slot: int = betterproto.uint32_field(2)


@dataclass
class CMsgMatchMetaDataContentsMatchInfo(betterproto.Message):
    duration_s: int = betterproto.uint32_field(1)
    match_outcome: "CMsgMatchMetaDataContentsEMatchOutcome" = betterproto.enum_field(2)
    winning_team: "ECitadelLobbyTeam" = betterproto.enum_field(3)
    players: List["CMsgMatchMetaDataContentsPlayers"] = betterproto.message_field(4)
    start_time: int = betterproto.uint32_field(5)
    match_id: int = betterproto.uint64_field(6)
    legacy_objectives_mask: int = betterproto.uint32_field(8)
    game_mode: "ECitadelGameMode" = betterproto.enum_field(9)
    match_mode: "ECitadelMatchMode" = betterproto.enum_field(10)
    objectives: List["CMsgMatchMetaDataContentsObjective"] = betterproto.message_field(
        11
    )
    match_paths: "CMsgMatchPlayerPathsData" = betterproto.message_field(12)
    damage_matrix: "CMsgMatchPlayerDamageMatrix" = betterproto.message_field(13)
    match_pauses: List["CMsgMatchMetaDataContentsPause"] = betterproto.message_field(14)
    custom_user_stats: List[
        "CMsgMatchMetaDataContentsCustomUserStatInfo"
    ] = betterproto.message_field(15)
    watched_death_replays: List[
        "CMsgMatchMetaDataContentsWatchedDeathReplay"
    ] = betterproto.message_field(16)
    objectives_mask_team0: int = betterproto.uint64_field(17)
    objectives_mask_team1: int = betterproto.uint64_field(18)
    mid_boss: List["CMsgMatchMetaDataContentsMidBoss"] = betterproto.message_field(19)


@dataclass
class CMsgMatchMetaData(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    match_details: bytes = betterproto.bytes_field(2)
    match_id: int = betterproto.uint64_field(3)


@dataclass
class CMsgMapLine(betterproto.Message):
    x: int = betterproto.int32_field(1)
    y: int = betterproto.int32_field(2)
    initial: bool = betterproto.bool_field(3)


@dataclass
class CMsgAccountHeroStats(betterproto.Message):
    hero_id: int = betterproto.uint32_field(1)
    stat_id: List[int] = betterproto.uint32_field(2)
    total_value: List[int] = betterproto.uint64_field(3)
    medals_bronze: List[int] = betterproto.uint32_field(4)
    medals_silver: List[int] = betterproto.uint32_field(5)
    medals_gold: List[int] = betterproto.uint32_field(6)


@dataclass
class CMsgAccountBookStats(betterproto.Message):
    book_id: int = betterproto.uint32_field(1)
    book_xp: int = betterproto.uint32_field(2)
    book_max_xp: int = betterproto.uint32_field(3)


@dataclass
class CMsgAccountStats(betterproto.Message):
    account_id: int = betterproto.uint32_field(1)
    stats: List["CMsgAccountHeroStats"] = betterproto.message_field(2)
