# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: citadel_usermessages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class CitadelUserMessageIds(betterproto.Enum):
    k_EUserMsg_Damage = 300
    k_EUserMsg_MapPing = 303
    k_EUserMsg_TeamRewards = 304
    k_EUserMsg_AbilityFailed = 306
    k_EUserMsg_TriggerDamageFlash = 308
    k_EUserMsg_AbilitiesChanged = 309
    k_EUserMsg_RecentDamageSummary = 310
    k_EUserMsg_SpectatorTeamChanged = 311
    k_EUserMsg_ChatWheel = 312
    k_EUserMsg_GoldHistory = 313
    k_EUserMsg_ChatMsg = 314
    k_EUserMsg_QuickResponse = 315
    k_EUserMsg_PostMatchDetails = 316
    k_EUserMsg_ChatEvent = 317
    k_EUserMsg_AbilityInterrupted = 318
    k_EUserMsg_HeroKilled = 319
    k_EUserMsg_ReturnIdol = 320
    k_EUserMsg_SetClientCameraAngles = 321
    k_EUserMsg_MapLine = 322
    k_EUserMsg_BulletHit = 323
    k_EUserMsg_ObjectiveMask = 324
    k_EUserMsg_ModifierApplied = 325
    k_EUserMsg_CameraController = 326
    k_EUserMsg_AuraModifierApplied = 327
    k_EUserMsg_ObstructedShotFired = 329
    k_EUserMsg_AbilityLateFailure = 330
    k_EUserMsg_AbilityPing = 331
    k_EUserMsg_PostProcessingAnim = 332
    k_EUserMsg_DeathReplayData = 333
    k_EUserMsg_PlayerLifetimeStatInfo = 334
    k_EUserMsg_ForceShopClosed = 336
    k_EUserMsg_StaminaDrained = 337
    k_EUserMsg_AbilityNotify = 338
    k_EUserMsg_GetDamageStatsResponse = 339
    k_EUserMsg_ParticipantStartSoundEvent = 340
    k_EUserMsg_ParticipantStopSoundEvent = 341
    k_EUserMsg_ParticipantStopSoundEventHash = 342
    k_EUserMsg_ParticipantSetSoundEventParams = 343
    k_EUserMsg_ParticipantSetLibraryStackFields = 344
    k_EUserMsg_CurrencyChanged = 345
    k_EUserMsg_GameOver = 346
    k_EUserMsg_BossKilled = 347
    k_EUserMsg_BossDamaged = 348
    k_EUserMsg_MidBossSpawned = 349
    k_EUserMsg_RejuvStatus = 350
    k_EUserMsg_KillStreak = 351
    k_EUserMsg_TeamMsg = 352
    k_EUserMsg_PlayerRespawned = 353
    k_EUserMsg_CallCheaterVote = 354


class CitadelEntityMessageIds(betterproto.Enum):
    k_EEntityMsg_BreakablePropSpawnDebris = 500


class ChatMsgPingMarkerInfo(betterproto.Enum):
    k_EPingMarkerInfo_ShowMarkerAndSound = 0
    k_EPingMarkerInfo_HideMarkerAndSound = 1
    k_EPingMarkerInfo_ShowMarkerOnSender = 2
    k_EPingMarkerInfo_OnlyShowMarker = 3
    k_EPingMarkerInfo_OnlyPlaySound = 4


class CameraOperation(betterproto.Enum):
    k_ECameraOp_Maintain = 2
    k_ECameraOp_Approach = 3
    k_ECameraOp_Spring = 4
    k_ECameraOp_Lerp = 5
    k_ECameraOp_Lag = 6


class CameraParam(betterproto.Enum):
    k_EParam_ClearAllOps = 0
    k_EParam_ClearAllOpsForContext = 1
    k_EParam_Distance = 2
    k_EParam_FOV = 3
    k_EParam_TargetPosition = 4
    k_EParam_VertOffset = 5
    k_EParam_HorizOffset = 6


class CameraParamMode(betterproto.Enum):
    k_EParamMode_AllowInOneContext = 0
    k_EParamMode_AllowInMultipleContexts = 1


class CameraAction(betterproto.Enum):
    k_EAction_AddOp = 0
    k_EAction_ClearAllOps = 1
    k_EAction_ClearOpsForContext = 2


class ECitadelChatMessage(betterproto.Enum):
    CITADEL_CHAT_MESSAGE_UNPAUSE_COUNTDOWN = 1
    CITADEL_CHAT_MESSAGE_UNPAUSED = 2
    CITADEL_CHAT_MESSAGE_AUTO_UNPAUSED = 3
    CITADEL_CHAT_MESSAGE_PAUSE_COUNTDOWN = 4
    CITADEL_CHAT_MESSAGE_PAUSED = 5
    CITADEL_CHAT_MESSAGE_YOUPAUSED = 6
    CITADEL_CHAT_MESSAGE_CANTPAUSE = 7
    CITADEL_CHAT_MESSAGE_CANTUNPAUSETEAM = 8
    CITADEL_CHAT_MESSAGE_NOPAUSESLEFT = 9
    CITADEL_CHAT_MESSAGE_CANTPAUSEYET = 10
    CITADEL_CHAT_MESSAGE_PREGAME_COUNTDOWN = 11
    CITADEL_CHAT_MESSAGE_NOTEAMPAUSESLEFT = 12
    CITADEL_CHAT_MESSAGE_COMMS_RESTRICTED = 13


class PostProcessingGameStates(betterproto.Enum):
    PostProcState_Killed = 0
    PostProcState_Black = 1
    PostProcState_Blinded = 2
    PostProcState_ShivPossessed = 3


class CCitadelUserMsg_AbilitiesChangedChange(betterproto.Enum):
    EInvalid = -1
    EPurchased = 0
    EUpgraded = 1
    ESold = 2
    ESwappedActivatedAbility = 3


@dataclass
class CUserMessageEmpty(betterproto.Message):
    empty: int = betterproto.uint32_field(1)


@dataclass
class CCitadelUserMessage_Damage(betterproto.Message):
    damage: int = betterproto.int32_field(1)
    pre_damage: int = betterproto.int32_field(2)
    type: int = betterproto.int32_field(3)
    citadel_type: int = betterproto.int32_field(4)
    origin: "CMsgVector" = betterproto.message_field(5)
    entindex_victim: int = betterproto.int32_field(6)
    entindex_inflictor: int = betterproto.int32_field(7)
    entindex_attacker: int = betterproto.int32_field(8)
    entindex_ability: int = betterproto.int32_field(9)
    damage_absorbed: int = betterproto.int32_field(10)
    victim_health_max: int = betterproto.int32_field(11)
    victim_health_new: int = betterproto.int32_field(12)
    flags: int = betterproto.uint64_field(13)
    ability_id: int = betterproto.uint32_field(14)
    attacker_class: int = betterproto.uint32_field(15)
    victim_class: int = betterproto.uint32_field(16)
    victim_shield_max: int = betterproto.int32_field(17)
    victim_shield_new: int = betterproto.int32_field(18)
    hits: int = betterproto.int32_field(19)
    health_lost: int = betterproto.int32_field(20)


@dataclass
class PingCommonData(betterproto.Message):
    ping_message_id: int = betterproto.uint32_field(1)
    ping_location: "CMsgVector" = betterproto.message_field(2)
    entity_index: int = betterproto.uint32_field(3)
    sender_player_slot: int = betterproto.int32_field(4)
    speech_concept: int = betterproto.int32_field(5)
    response_chosen: str = betterproto.string_field(6)
    cooldown_time: float = betterproto.float_field(7)


@dataclass
class CCitadelUserMsg_MapPing(betterproto.Message):
    ping_data: "PingCommonData" = betterproto.message_field(1)
    event_type: int = betterproto.uint32_field(2)
    ping_marker_and_sound_info: "ChatMsgPingMarkerInfo" = betterproto.enum_field(3)
    pinged_enemy_entity: bool = betterproto.bool_field(4)
    pinged_entity_class: int = betterproto.uint32_field(5)
    is_minimap_ping: bool = betterproto.bool_field(6)
    pinged_hero_name: str = betterproto.string_field(7)
    is_blind_ping: bool = betterproto.bool_field(8)


@dataclass
class CCitadelUserMsg_PingWheel(betterproto.Message):
    ping_data: "PingCommonData" = betterproto.message_field(1)
    ping_wheel_option_id: int = betterproto.uint32_field(2)


@dataclass
class CCitadelUserMsg_AbilityPing(betterproto.Message):
    ping_data: "PingCommonData" = betterproto.message_field(1)
    ability_id: int = betterproto.uint32_field(2)
    ability_cooldown: float = betterproto.float_field(3)
    ping_marker_and_sound_info: "ChatMsgPingMarkerInfo" = betterproto.enum_field(4)


@dataclass
class CCitadelUserMsg_QuickResponse(betterproto.Message):
    ping_data: "PingCommonData" = betterproto.message_field(1)
    responding_to_ping_message_id: int = betterproto.uint32_field(2)
    responding_to_player_slot: int = betterproto.int32_field(3)
    lane_color: "CMsgLaneColor" = betterproto.enum_field(4)


@dataclass
class CCitadelUserMsg_MapLine(betterproto.Message):
    sender_player_slot: int = betterproto.int32_field(1)
    mapline: "CMsgMapLine" = betterproto.message_field(2)


@dataclass
class CCitadelUserMsg_TeamRewards(betterproto.Message):
    xp: int = betterproto.uint32_field(1)
    gold: int = betterproto.uint32_field(2)
    winner: bool = betterproto.bool_field(3)


@dataclass
class CCitadelUserMsg_TriggerDamageFlash(betterproto.Message):
    entindex_flash_victim: int = betterproto.int32_field(1)
    entindex_flash_attacker: int = betterproto.int32_field(2)
    entindex_flash_hitgroup: int = betterproto.int32_field(3)
    flash_value: int = betterproto.uint32_field(4)
    flash_type: int = betterproto.uint32_field(5)
    flash_flags: int = betterproto.uint32_field(6)
    flash_position: "CMsgVector" = betterproto.message_field(7)


@dataclass
class CCitadelUserMsg_AbilitiesChanged(betterproto.Message):
    entindex_purchaser: int = betterproto.int32_field(1)
    entindex_ability: int = betterproto.int32_field(2)
    ability_id: int = betterproto.uint32_field(3)
    change: "CCitadelUserMsg_AbilitiesChangedChange" = betterproto.enum_field(4)


@dataclass
class CCitadelUserMsg_AbilityInterrupted(betterproto.Message):
    entindex_victim: int = betterproto.int32_field(1)
    entindex_interrupter: int = betterproto.int32_field(2)
    ability_id_interrupted: int = betterproto.uint32_field(3)
    ability_id_interrupter: int = betterproto.uint32_field(4)
    hero_id_interrupter: int = betterproto.uint32_field(5)


@dataclass
class CCitadelUserMsg_AbilityLateFailure(betterproto.Message):
    entindex_caster: int = betterproto.int32_field(1)
    entindex_ability: int = betterproto.int32_field(2)
    failure_type: int = betterproto.uint32_field(3)


@dataclass
class CCitadelUserMsg_RecentDamageSummary(betterproto.Message):
    player_slot: int = betterproto.int32_field(1)
    damage_records: List[
        "CCitadelUserMsg_RecentDamageSummaryDamageRecord"
    ] = betterproto.message_field(2)
    start_time: float = betterproto.float_field(3)
    end_time: float = betterproto.float_field(4)
    total_damage: int = betterproto.int32_field(5)
    lost_gold: int = betterproto.int32_field(6)
    modifier_records: List[
        "CCitadelUserMsg_RecentDamageSummaryModifierRecord"
    ] = betterproto.message_field(7)


@dataclass
class CCitadelUserMsg_RecentDamageSummaryDamageRecord(betterproto.Message):
    damage: int = betterproto.int32_field(1)
    hits: int = betterproto.int32_field(2)
    damage_type: int = betterproto.uint32_field(3)
    hero_id: int = betterproto.uint32_field(4)
    ability_id: int = betterproto.uint32_field(5)
    attacker_class: int = betterproto.uint32_field(6)
    damage_absorbed: int = betterproto.int32_field(7)
    is_killing_blow: bool = betterproto.bool_field(8)
    victim_hero_id: int = betterproto.uint32_field(9)


@dataclass
class CCitadelUserMsg_RecentDamageSummaryModifierRecord(betterproto.Message):
    ability_id: int = betterproto.uint32_field(1)
    modifier_type_id: int = betterproto.uint32_field(2)
    entindex_caster: int = betterproto.int32_field(3)
    start_time: float = betterproto.float_field(4)
    end_time: float = betterproto.float_field(5)
    debuff: bool = betterproto.bool_field(6)


@dataclass
class CCitadelUserMsg_SpectatorTeamChanged(betterproto.Message):
    teamnumber: int = betterproto.int32_field(1)


@dataclass
class CCitadelUserMsg_ChatWheel(betterproto.Message):
    chat_message_id: int = betterproto.uint32_field(1)
    player_slot: int = betterproto.int32_field(2)
    pawn_entindex: int = betterproto.int32_field(3)
    account_id: int = betterproto.uint32_field(4)
    hero_id: int = betterproto.uint32_field(5)
    param_1: str = betterproto.string_field(6)
    lane_color: "CMsgLaneColor" = betterproto.enum_field(7)


@dataclass
class CCitadelUserMsg_ChatMsg(betterproto.Message):
    player_slot: int = betterproto.int32_field(1)
    text: str = betterproto.string_field(2)
    all_chat: bool = betterproto.bool_field(3)
    lane_color: "CMsgLaneColor" = betterproto.enum_field(4)


@dataclass
class CCitadelUserMsg_GoldHistory(betterproto.Message):
    entindex_player: int = betterproto.int32_field(1)
    minute_records: List[
        "CCitadelUserMsg_GoldHistoryMinuteRecord"
    ] = betterproto.message_field(2)


@dataclass
class CCitadelUserMsg_GoldHistoryGoldRecord(betterproto.Message):
    currency_source: int = betterproto.int32_field(1)
    gold: int = betterproto.int32_field(2)
    events: int = betterproto.int32_field(3)


@dataclass
class CCitadelUserMsg_GoldHistoryMinuteRecord(betterproto.Message):
    match_minute: int = betterproto.int32_field(1)
    gold_records: List[
        "CCitadelUserMsg_GoldHistoryGoldRecord"
    ] = betterproto.message_field(2)


@dataclass
class CCitadelUserMsg_CameraController(betterproto.Message):
    action: "CameraAction" = betterproto.enum_field(1)
    operation: "CameraOperation" = betterproto.enum_field(2)
    param: "CameraParam" = betterproto.enum_field(3)
    param_mode: "CameraParamMode" = betterproto.enum_field(12)
    delay: float = betterproto.float_field(4)
    relative_values: bool = betterproto.bool_field(11)
    context_symbol_id: int = betterproto.uint32_field(5)
    priority: int = betterproto.uint32_field(13)
    maintain: "CCitadelUserMsg_CameraControllerMaintain" = betterproto.message_field(6)
    approach: "CCitadelUserMsg_CameraControllerApproach" = betterproto.message_field(7)
    spring: "CCitadelUserMsg_CameraControllerSpring" = betterproto.message_field(8)
    lerp: "CCitadelUserMsg_CameraControllerLerp" = betterproto.message_field(9)
    lag: "CCitadelUserMsg_CameraControllerLag" = betterproto.message_field(10)


@dataclass
class CCitadelUserMsg_CameraControllerMaintain(betterproto.Message):
    duration: float = betterproto.float_field(1)
    maintain_vector: "CMsgVector" = betterproto.message_field(2)
    maintain_float: float = betterproto.float_field(3)
    maintain_current: bool = betterproto.bool_field(4)


@dataclass
class CCitadelUserMsg_CameraControllerApproach(betterproto.Message):
    speed: float = betterproto.float_field(1)
    default_speed: float = betterproto.float_field(2)
    acceleration: float = betterproto.float_field(3)
    min_duration: float = betterproto.float_field(4)
    approach_float: float = betterproto.float_field(5)
    approach_vector: "CMsgVector" = betterproto.message_field(6)
    chase_default: bool = betterproto.bool_field(7)


@dataclass
class CCitadelUserMsg_CameraControllerSpring(betterproto.Message):
    spring_strength: float = betterproto.float_field(1)
    min_speed: float = betterproto.float_field(4)
    max_duration: float = betterproto.float_field(5)
    target_float: float = betterproto.float_field(6)
    target_vector: "CMsgVector" = betterproto.message_field(7)


@dataclass
class CCitadelUserMsg_CameraControllerLerp(betterproto.Message):
    start_float: float = betterproto.float_field(1)
    start_vector: "CMsgVector" = betterproto.message_field(2)
    end_float: float = betterproto.float_field(3)
    end_vector: "CMsgVector" = betterproto.message_field(4)
    bias: float = betterproto.float_field(5)
    gain: float = betterproto.float_field(6)
    duration: float = betterproto.float_field(7)


@dataclass
class CCitadelUserMsg_CameraControllerLag(betterproto.Message):
    min_duration: float = betterproto.float_field(1)
    lag_time: float = betterproto.float_field(2)
    max_speed: float = betterproto.float_field(3)
    spring_strength: float = betterproto.float_field(4)
    increase_spring_strength_to_keep_target_on_screen: bool = betterproto.bool_field(5)


@dataclass
class CCitadelUserMsg_PostMatchDetails(betterproto.Message):
    match_details: bytes = betterproto.bytes_field(1)


@dataclass
class CCitadelUserMsg_ChatEvent(betterproto.Message):
    type: "ECitadelChatMessage" = betterproto.enum_field(1)
    values: List[int] = betterproto.uint32_field(2)
    player_slots: List[int] = betterproto.int32_field(3)


@dataclass
class CCitadelUserMsg_HeroKilled(betterproto.Message):
    entindex_victim: int = betterproto.int32_field(1)
    entindex_inflictor: int = betterproto.int32_field(2)
    entindex_attacker: int = betterproto.int32_field(3)
    entindex_assisters: List[int] = betterproto.int32_field(4)
    entindex_scorer: int = betterproto.int32_field(5)
    respawn_reason: int = betterproto.int32_field(6)


@dataclass
class CCitadelEntityMsg_BreakablePropSpawnDebris(betterproto.Message):
    entity_msg: "CEntityMsg" = betterproto.message_field(1)
    damage_pos: "CMsgVector" = betterproto.message_field(2)
    damage: float = betterproto.float_field(3)


@dataclass
class CCitadelUserMsg_ReturnIdol(betterproto.Message):
    location_index: int = betterproto.int32_field(1)
    return_location: "CMsgVector" = betterproto.message_field(2)
    location_enabled: bool = betterproto.bool_field(3)


@dataclass
class CCitadelUserMsg_SetClientCameraAngles(betterproto.Message):
    player_slot: int = betterproto.int32_field(1)
    camera_angles: "CMsgQAngle" = betterproto.message_field(2)


@dataclass
class CCitadelUserMessage_BulletHit(betterproto.Message):
    shotid: int = betterproto.int32_field(1)
    pellet: int = betterproto.int32_field(2)
    hit_entindex: int = betterproto.int32_field(3)


@dataclass
class CCitadelUserMessage_ObjectiveMask(betterproto.Message):
    objective_mask_team0: int = betterproto.uint64_field(2)
    objective_mask_team1: int = betterproto.uint64_field(3)


@dataclass
class CCitadelUserMessage_ModifierApplied(betterproto.Message):
    entindex_caster: int = betterproto.int32_field(1)
    entindex_parent: int = betterproto.int32_field(2)
    serial_number: int = betterproto.int32_field(3)


@dataclass
class CCitadelUserMessage_AuraModifierApplied(betterproto.Message):
    entindex_caster: int = betterproto.int32_field(1)
    entindex_target: int = betterproto.int32_field(2)
    modifier_type_id: int = betterproto.uint32_field(3)
    modifier_serial_number: int = betterproto.int32_field(4)
    aura_start_time: float = betterproto.float_field(5)
    aura_end_time: float = betterproto.float_field(6)


@dataclass
class CCitadelUserMsg_ObstructedShotFired(betterproto.Message):
    pass


@dataclass
class CCitadelUserMsg_PostProcessingAnim(betterproto.Message):
    entindex_owner: int = betterproto.int32_field(1)
    clear_all_states: bool = betterproto.bool_field(2)
    state: "PostProcessingGameStates" = betterproto.enum_field(3)
    start_time: float = betterproto.float_field(4)
    fade_in_time: float = betterproto.float_field(5)
    hold_time: float = betterproto.float_field(6)
    fade_out_time: float = betterproto.float_field(7)
    scale: float = betterproto.float_field(8)


@dataclass
class CCitadelUserMsg_DeathReplayData(betterproto.Message):
    killer_scorer: int = betterproto.int32_field(1)
    killer_inflictor: int = betterproto.int32_field(2)
    damage_summary: "CCitadelUserMsg_RecentDamageSummary" = betterproto.message_field(3)


@dataclass
class CCitadelUserMsg_ForceShopClosed(betterproto.Message):
    pass


@dataclass
class CCitadelUserMsg_PlayerLifetimeStatInfo(betterproto.Message):
    stats: List[
        "CCitadelUserMsg_PlayerLifetimeStatInfoStat"
    ] = betterproto.message_field(1)
    match_id: int = betterproto.uint64_field(2)
    end_of_match: bool = betterproto.bool_field(3)
    is_official_match: bool = betterproto.bool_field(4)


@dataclass
class CCitadelUserMsg_PlayerLifetimeStatInfoStat(betterproto.Message):
    stat_name: str = betterproto.string_field(1)
    match_total: int = betterproto.uint32_field(2)
    lifetime_value: int = betterproto.uint32_field(3)
    priority: int = betterproto.uint32_field(4)
    prev_lifetime_max: int = betterproto.uint32_field(5)
    stat_type: int = betterproto.uint32_field(6)
    stat_type_id: int = betterproto.uint32_field(7)


@dataclass
class CCitadelUserMsg_StaminaDrained(betterproto.Message):
    entindex_victim: int = betterproto.int32_field(1)
    stamina_drained: int = betterproto.int32_field(2)


@dataclass
class CCitadelUserMessage_AbilityNotify(betterproto.Message):
    entindex_victim: int = betterproto.int32_field(1)
    entindex_attacker: int = betterproto.int32_field(2)
    ability_id: int = betterproto.uint32_field(3)


@dataclass
class CCitadelUserMessage_CurrencyChanged(betterproto.Message):
    entindex_hero_pawn: int = betterproto.int32_field(1)
    currency_type: int = betterproto.int32_field(2)
    currency_source: int = betterproto.int32_field(3)
    delta: int = betterproto.int32_field(4)
    notification: bool = betterproto.bool_field(5)
    entindex_victim: int = betterproto.int32_field(6)
    victim_pos: "CMsgVector" = betterproto.message_field(7)
    playsound: int = betterproto.int32_field(8)
    ability_id: int = betterproto.uint32_field(9)


@dataclass
class CCitadelUserMessage_GameOver(betterproto.Message):
    winning_team: int = betterproto.int32_field(1)
    just_a_test: bool = betterproto.bool_field(2)


@dataclass
class CCitadelUserMsg_GetDamageStatsResponse(betterproto.Message):
    player_slot: int = betterproto.uint32_field(1)
    ability_name: str = betterproto.string_field(2)
    damage: "CCitadelUserMsg_GetDamageStatsResponseStatType" = (
        betterproto.message_field(3)
    )
    healing: "CCitadelUserMsg_GetDamageStatsResponseStatType" = (
        betterproto.message_field(4)
    )


@dataclass
class CCitadelUserMsg_GetDamageStatsResponseStatType(betterproto.Message):
    target_player_slot: List[int] = betterproto.uint32_field(1)
    value: List[int] = betterproto.uint32_field(2)


@dataclass
class CCitadelUserMsg_ParticipantStartSoundEvent(betterproto.Message):
    event: "CMsgSosStartSoundEvent" = betterproto.message_field(1)
    player_slots: List[int] = betterproto.int32_field(2)


@dataclass
class CCitadelUserMsg_ParticipantStopSoundEvent(betterproto.Message):
    event: "CMsgSosStopSoundEvent" = betterproto.message_field(1)
    player_slots: List[int] = betterproto.int32_field(2)


@dataclass
class CCitadelUserMsg_ParticipantStopSoundEventHash(betterproto.Message):
    event: "CMsgSosStopSoundEventHash" = betterproto.message_field(1)
    player_slots: List[int] = betterproto.int32_field(2)


@dataclass
class CCitadelUserMsg_ParticipantSetSoundEventParams(betterproto.Message):
    event: "CMsgSosSetSoundEventParams" = betterproto.message_field(1)
    player_slots: List[int] = betterproto.int32_field(2)


@dataclass
class CCitadelUserMsg_ParticipantSetLibraryStackFields(betterproto.Message):
    event: "CMsgSosSetLibraryStackFields" = betterproto.message_field(1)
    player_slots: List[int] = betterproto.int32_field(2)


@dataclass
class CCitadelUserMsg_BossKilled(betterproto.Message):
    objective_team: int = betterproto.int32_field(1)
    objective_mask_change: int = betterproto.int32_field(2)
    entity_killed: int = betterproto.uint32_field(3)
    entity_killed_class: int = betterproto.int32_field(4)
    entity_killer: int = betterproto.uint32_field(5)
    gametime: float = betterproto.float_field(6)
    bosses_remaining: int = betterproto.int32_field(7)


@dataclass
class CCitadelUserMsg_BossDamaged(betterproto.Message):
    objective_team: int = betterproto.int32_field(1)
    objective_id: int = betterproto.int32_field(2)
    entity_damaged: int = betterproto.uint32_field(3)


@dataclass
class CCitadelUserMsg_MidBossSpawned(betterproto.Message):
    pass


@dataclass
class CCitadelUserMsg_RejuvStatus(betterproto.Message):
    killing_team: int = betterproto.int32_field(1)
    player_pawn: int = betterproto.uint32_field(2)
    user_team: int = betterproto.int32_field(3)
    event_type: int = betterproto.int32_field(4)


@dataclass
class CCitadelUserMsg_KillStreak(betterproto.Message):
    player_pawn: int = betterproto.uint32_field(1)
    num_kills: int = betterproto.int32_field(2)
    is_first_blood: bool = betterproto.bool_field(3)


@dataclass
class CCitadelUserMsg_TeamMsg(betterproto.Message):
    event_type: int = betterproto.int32_field(1)
    team_number: int = betterproto.int32_field(2)
    lane_color: int = betterproto.int32_field(3)
    player_controller: int = betterproto.uint32_field(4)


@dataclass
class CCitadelUserMsg_PlayerRespawned(betterproto.Message):
    player_pawn: int = betterproto.uint32_field(1)
    facing_yaw: float = betterproto.float_field(2)


@dataclass
class CCitadelUserMsg_CallCheaterVote(betterproto.Message):
    player_slot: int = betterproto.int32_field(1)
