# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: citadel_gamemessages.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class ECitadelGameMessages(betterproto.Enum):
    k_EMsgGameServerToClientConnectionStatus = 10
    k_EMsgGameServerToClientInitialGameState = 12
    k_EMsgGameServerToClientGameCompleted = 13
    k_EMsgGameServerToClientGoodbye = 15


class ECitadelDisconnectReason(betterproto.Enum):
    k_ECitadelDisconnectReason_UserLeaveMatch = 1001
    k_ECitadelDisconnectReason_UserQuitApp = 1002
    k_ECitadelDisconnectReason_UserCancel = 1003
    k_ECitadelDisconnectReason_Goodbye = 1004
    k_ECitadelDisconnectReason_BadMessage = 2001
    k_ECitadelDisconnectReason_GameDestroyedUnexpectedly = 2002
    k_ECitadelDisconnectReason_ChangingServer = 2003
    k_ECitadelDisconnectReason_OldConnection = 2004
    k_ECitadelDisconnectReason_GoodbyeUnrecognizedGame = 2005


class CMsgGameServerToClientConnectionStatusEStatus(betterproto.Enum):
    k_EConnected = 1
    k_EDisconnected = 2


@dataclass
class CMsgClientServerHeader(betterproto.Message):
    game_instance_id: int = betterproto.uint64_field(1)
    local_player_index: int = betterproto.uint32_field(2)
    payload: bytes = betterproto.bytes_field(3)
    msg_id: "ECitadelGameMessages" = betterproto.enum_field(4)


@dataclass
class CMsgGameServerToClientGameCompleted(betterproto.Message):
    pass


@dataclass
class CMsgGameServerToClientGoodbye(betterproto.Message):
    pass


@dataclass
class CMsgGameServerToClientConnectionStatus(betterproto.Message):
    players: List[
        "CMsgGameServerToClientConnectionStatusPlayer"
    ] = betterproto.message_field(1)


@dataclass
class CMsgGameServerToClientConnectionStatusPlayer(betterproto.Message):
    player_slot: int = betterproto.int32_field(1)
    status: "CMsgGameServerToClientConnectionStatusEStatus" = betterproto.enum_field(2)
    inactivity_ticking: bool = betterproto.bool_field(3)
    inactivity_ms_remaining: int = betterproto.uint32_field(4)
    inactivity_anim_ms_remaining: int = betterproto.uint32_field(5)


@dataclass
class CClientReconnectInfo(betterproto.Message):
    server_steam_id: float = betterproto.fixed64_field(1)
    lobby_id: int = betterproto.uint64_field(2)
    time_updated: int = betterproto.uint32_field(3)
    udp_connect_ip: int = betterproto.uint32_field(4)
    udp_connect_port: int = betterproto.uint32_field(5)
    compatibility_version: int = betterproto.uint32_field(6)


@dataclass
class CMsgClientAccountSyncStorageFile(betterproto.Message):
    version: int = betterproto.uint32_field(1)
    ids: List[int] = betterproto.uint32_field(2)
    values: List[int] = betterproto.uint32_field(3)
