# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: gameevents.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class EBaseGameEvents(betterproto.Enum):
    GE_VDebugGameSessionIDEvent = 200
    GE_PlaceDecalEvent = 201
    GE_ClearWorldDecalsEvent = 202
    GE_ClearEntityDecalsEvent = 203
    GE_ClearDecalsForSkeletonInstanceEvent = 204
    GE_Source1LegacyGameEventList = 205
    GE_Source1LegacyListenEvents = 206
    GE_Source1LegacyGameEvent = 207
    GE_SosStartSoundEvent = 208
    GE_SosStopSoundEvent = 209
    GE_SosSetSoundEventParams = 210
    GE_SosSetLibraryStackFields = 211
    GE_SosStopSoundEventHash = 212


@dataclass
class CMsgVDebugGameSessionIDEvent(betterproto.Message):
    clientid: int = betterproto.int32_field(1)
    gamesessionid: str = betterproto.string_field(2)


@dataclass
class CMsgPlaceDecalEvent(betterproto.Message):
    position: "CMsgVector" = betterproto.message_field(1)
    normal: "CMsgVector" = betterproto.message_field(2)
    saxis: "CMsgVector" = betterproto.message_field(3)
    decalmaterialindex: int = betterproto.uint32_field(4)
    flags: int = betterproto.uint32_field(5)
    color: float = betterproto.fixed32_field(6)
    width: float = betterproto.float_field(7)
    height: float = betterproto.float_field(8)
    depth: float = betterproto.float_field(9)
    entityhandleindex: int = betterproto.uint32_field(10)
    skeletoninstancehash: float = betterproto.fixed32_field(11)
    boneindex: int = betterproto.int32_field(12)
    translucenthit: bool = betterproto.bool_field(13)
    is_adjacent: bool = betterproto.bool_field(14)


@dataclass
class CMsgClearWorldDecalsEvent(betterproto.Message):
    flagstoclear: int = betterproto.uint32_field(1)


@dataclass
class CMsgClearEntityDecalsEvent(betterproto.Message):
    flagstoclear: int = betterproto.uint32_field(1)


@dataclass
class CMsgClearDecalsForSkeletonInstanceEvent(betterproto.Message):
    flagstoclear: int = betterproto.uint32_field(1)
    entityhandleindex: int = betterproto.uint32_field(2)
    skeletoninstancehash: int = betterproto.uint32_field(3)


@dataclass
class CMsgSource1LegacyGameEventList(betterproto.Message):
    descriptors: List[
        "CMsgSource1LegacyGameEventListDescriptorT"
    ] = betterproto.message_field(1)


@dataclass
class CMsgSource1LegacyGameEventListkeyT(betterproto.Message):
    type: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)


@dataclass
class CMsgSource1LegacyGameEventListdescriptorT(betterproto.Message):
    eventid: int = betterproto.int32_field(1)
    name: str = betterproto.string_field(2)
    keys: List["CMsgSource1LegacyGameEventListKeyT"] = betterproto.message_field(3)


@dataclass
class CMsgSource1LegacyListenEvents(betterproto.Message):
    playerslot: int = betterproto.int32_field(1)
    eventarraybits: List[int] = betterproto.uint32_field(2)


@dataclass
class CMsgSource1LegacyGameEvent(betterproto.Message):
    event_name: str = betterproto.string_field(1)
    eventid: int = betterproto.int32_field(2)
    keys: List["CMsgSource1LegacyGameEventKeyT"] = betterproto.message_field(3)
    server_tick: int = betterproto.int32_field(4)
    passthrough: int = betterproto.int32_field(5)


@dataclass
class CMsgSource1LegacyGameEventkeyT(betterproto.Message):
    type: int = betterproto.int32_field(1)
    val_string: str = betterproto.string_field(2)
    val_float: float = betterproto.float_field(3)
    val_long: int = betterproto.int32_field(4)
    val_short: int = betterproto.int32_field(5)
    val_byte: int = betterproto.int32_field(6)
    val_bool: bool = betterproto.bool_field(7)
    val_uint64: int = betterproto.uint64_field(8)


@dataclass
class CMsgSosStartSoundEvent(betterproto.Message):
    soundevent_guid: int = betterproto.int32_field(1)
    soundevent_hash: float = betterproto.fixed32_field(2)
    source_entity_index: int = betterproto.int32_field(3)
    seed: int = betterproto.int32_field(4)
    packed_params: bytes = betterproto.bytes_field(5)
    start_time: float = betterproto.float_field(6)


@dataclass
class CMsgSosStopSoundEvent(betterproto.Message):
    soundevent_guid: int = betterproto.int32_field(1)


@dataclass
class CMsgSosStopSoundEventHash(betterproto.Message):
    soundevent_hash: float = betterproto.fixed32_field(1)
    source_entity_index: int = betterproto.int32_field(2)


@dataclass
class CMsgSosSetSoundEventParams(betterproto.Message):
    soundevent_guid: int = betterproto.int32_field(1)
    packed_params: bytes = betterproto.bytes_field(5)


@dataclass
class CMsgSosSetLibraryStackFields(betterproto.Message):
    stack_hash: float = betterproto.fixed32_field(1)
    packed_fields: bytes = betterproto.bytes_field(5)
