# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: steamnetworkingsockets_messages_udp.proto
# plugin: python-betterproto
from dataclasses import dataclass

import betterproto


class ESteamNetworkingUDPMsgID(betterproto.Enum):
    k_ESteamNetworkingUDPMsg_ChallengeRequest = 32
    k_ESteamNetworkingUDPMsg_ChallengeReply = 33
    k_ESteamNetworkingUDPMsg_ConnectRequest = 34
    k_ESteamNetworkingUDPMsg_ConnectOK = 35
    k_ESteamNetworkingUDPMsg_ConnectionClosed = 36
    k_ESteamNetworkingUDPMsg_NoConnection = 37


class CMsgSteamSockets_UDP_StatsFlags(betterproto.Enum):
    ACK_REQUEST_E2E = 2
    ACK_REQUEST_IMMEDIATE = 4
    NOT_PRIMARY_TRANSPORT_E2E = 16


@dataclass
class CMsgSteamSockets_UDP_ChallengeRequest(betterproto.Message):
    connection_id: float = betterproto.fixed32_field(1)
    my_timestamp: float = betterproto.fixed64_field(3)
    protocol_version: int = betterproto.uint32_field(4)


@dataclass
class CMsgSteamSockets_UDP_ChallengeReply(betterproto.Message):
    connection_id: float = betterproto.fixed32_field(1)
    challenge: float = betterproto.fixed64_field(2)
    your_timestamp: float = betterproto.fixed64_field(3)
    protocol_version: int = betterproto.uint32_field(4)


@dataclass
class CMsgSteamSockets_UDP_ConnectRequest(betterproto.Message):
    client_connection_id: float = betterproto.fixed32_field(1)
    challenge: float = betterproto.fixed64_field(2)
    my_timestamp: float = betterproto.fixed64_field(5)
    ping_est_ms: int = betterproto.uint32_field(6)
    crypt: "CMsgSteamDatagramSessionCryptInfoSigned" = betterproto.message_field(7)
    cert: "CMsgSteamDatagramCertificateSigned" = betterproto.message_field(4)
    legacy_protocol_version: int = betterproto.uint32_field(8)
    identity_string: str = betterproto.string_field(10)
    legacy_client_steam_id: float = betterproto.fixed64_field(3)
    legacy_identity_binary: "CMsgSteamNetworkingIdentityLegacyBinary" = (
        betterproto.message_field(9)
    )


@dataclass
class CMsgSteamSockets_UDP_ConnectOK(betterproto.Message):
    client_connection_id: float = betterproto.fixed32_field(1)
    server_connection_id: float = betterproto.fixed32_field(5)
    your_timestamp: float = betterproto.fixed64_field(3)
    delay_time_usec: int = betterproto.uint32_field(4)
    crypt: "CMsgSteamDatagramSessionCryptInfoSigned" = betterproto.message_field(7)
    cert: "CMsgSteamDatagramCertificateSigned" = betterproto.message_field(8)
    identity_string: str = betterproto.string_field(11)
    legacy_server_steam_id: float = betterproto.fixed64_field(2)
    legacy_identity_binary: "CMsgSteamNetworkingIdentityLegacyBinary" = (
        betterproto.message_field(10)
    )


@dataclass
class CMsgSteamSockets_UDP_ConnectionClosed(betterproto.Message):
    to_connection_id: float = betterproto.fixed32_field(4)
    from_connection_id: float = betterproto.fixed32_field(5)
    debug: str = betterproto.string_field(2)
    reason_code: int = betterproto.uint32_field(3)


@dataclass
class CMsgSteamSockets_UDP_NoConnection(betterproto.Message):
    from_connection_id: float = betterproto.fixed32_field(2)
    to_connection_id: float = betterproto.fixed32_field(3)


@dataclass
class CMsgSteamSockets_UDP_Stats(betterproto.Message):
    stats: "CMsgSteamDatagramConnectionQuality" = betterproto.message_field(1)
    flags: int = betterproto.uint32_field(3)
