# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: steamdatagram_messages_auth.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


@dataclass
class CMsgSteamDatagramRelayAuthTicket(betterproto.Message):
    time_expiry: float = betterproto.fixed32_field(1)
    authorized_client_identity_string: str = betterproto.string_field(14)
    gameserver_identity_string: str = betterproto.string_field(15)
    authorized_public_ip: float = betterproto.fixed32_field(3)
    gameserver_address: bytes = betterproto.bytes_field(11)
    app_id: int = betterproto.uint32_field(7)
    virtual_port: int = betterproto.uint32_field(10)
    extra_fields: List[
        "CMsgSteamDatagramRelayAuthTicketExtraField"
    ] = betterproto.message_field(8)
    legacy_authorized_steam_id: float = betterproto.fixed64_field(2)
    legacy_gameserver_steam_id: float = betterproto.fixed64_field(4)
    legacy_gameserver_pop_id: float = betterproto.fixed32_field(9)
    legacy_authorized_client_identity_binary: bytes = betterproto.bytes_field(12)
    legacy_gameserver_identity_binary: bytes = betterproto.bytes_field(13)


@dataclass
class CMsgSteamDatagramRelayAuthTicketExtraField(betterproto.Message):
    name: str = betterproto.string_field(1)
    string_value: str = betterproto.string_field(2)
    int64_value: int = betterproto.sint64_field(3)
    fixed64_value: float = betterproto.fixed64_field(5)


@dataclass
class CMsgSteamDatagramSignedRelayAuthTicket(betterproto.Message):
    reserved_do_not_use: float = betterproto.fixed64_field(1)
    ticket: bytes = betterproto.bytes_field(3)
    signature: bytes = betterproto.bytes_field(4)
    key_id: float = betterproto.fixed64_field(2)
    certs: List["CMsgSteamDatagramCertificateSigned"] = betterproto.message_field(5)


@dataclass
class CMsgSteamDatagramCachedCredentialsForApp(betterproto.Message):
    private_key: bytes = betterproto.bytes_field(1)
    cert: bytes = betterproto.bytes_field(2)
    relay_tickets: List[bytes] = betterproto.bytes_field(3)


@dataclass
class CMsgSteamDatagramGameCoordinatorServerLogin(betterproto.Message):
    time_generated: int = betterproto.uint32_field(1)
    appid: int = betterproto.uint32_field(2)
    routing: bytes = betterproto.bytes_field(3)
    appdata: bytes = betterproto.bytes_field(4)
    legacy_identity_binary: bytes = betterproto.bytes_field(5)
    identity_string: str = betterproto.string_field(6)
    dummy_steam_id: float = betterproto.fixed64_field(99)


@dataclass
class CMsgSteamDatagramSignedGameCoordinatorServerLogin(betterproto.Message):
    cert: "CMsgSteamDatagramCertificateSigned" = betterproto.message_field(1)
    login: bytes = betterproto.bytes_field(2)
    signature: bytes = betterproto.bytes_field(3)


@dataclass
class CMsgSteamDatagramHostedServerAddressPlaintext(betterproto.Message):
    ipv4: float = betterproto.fixed32_field(1)
    ipv6: bytes = betterproto.bytes_field(2)
    port: int = betterproto.uint32_field(3)
    routing_secret: float = betterproto.fixed64_field(4)
    protocol_version: int = betterproto.uint32_field(5)
